# CMake generated Testfile for 
# Source directory: /home/user/axiam-c-sdk/tests
# Build directory: /home/user/axiam-c-sdk/build-asan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_config "/home/user/axiam-c-sdk/build-asan/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;30;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_version_policy "/home/user/axiam-c-sdk/build-asan/tests/test_version_policy")
set_tests_properties(test_version_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;35;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_sensitive "/home/user/axiam-c-sdk/build-asan/tests/test_sensitive")
set_tests_properties(test_sensitive PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;38;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_error "/home/user/axiam-c-sdk/build-asan/tests/test_error")
set_tests_properties(test_error PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;39;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_client_auth "/home/user/axiam-c-sdk/build-asan/tests/test_client_auth")
set_tests_properties(test_client_auth PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;40;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_client_failing_transport "/home/user/axiam-c-sdk/build-asan/tests/test_client_failing_transport")
set_tests_properties(test_client_failing_transport PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;41;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_authz "/home/user/axiam-c-sdk/build-asan/tests/test_authz")
set_tests_properties(test_authz PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;42;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_singleflight "/home/user/axiam-c-sdk/build-asan/tests/test_singleflight")
set_tests_properties(test_singleflight PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;43;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_refresh_org "/home/user/axiam-c-sdk/build-asan/tests/test_refresh_org")
set_tests_properties(test_refresh_org PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;44;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_integration_curl "/home/user/axiam-c-sdk/build-asan/tests/test_integration_curl")
set_tests_properties(test_integration_curl PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;45;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_webhook "/home/user/axiam-c-sdk/build-asan/tests/test_webhook")
set_tests_properties(test_webhook PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;46;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_uma "/home/user/axiam-c-sdk/build-asan/tests/test_uma")
set_tests_properties(test_uma PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;47;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_uma_branches "/home/user/axiam-c-sdk/build-asan/tests/test_uma_branches")
set_tests_properties(test_uma_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;48;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_opaque_binding "/home/user/axiam-c-sdk/build-asan/tests/test_opaque_binding")
set_tests_properties(test_opaque_binding PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;71;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_opaque_login "/home/user/axiam-c-sdk/build-asan/tests/test_opaque_login")
set_tests_properties(test_opaque_login PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;72;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_d5_conformance "/home/user/axiam-c-sdk/build-asan/tests/test_d5_conformance")
set_tests_properties(test_d5_conformance PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;85;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_client_branches "/home/user/axiam-c-sdk/build-asan/tests/test_client_branches")
set_tests_properties(test_client_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;88;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_client_null_args "/home/user/axiam-c-sdk/build-asan/tests/test_client_null_args")
set_tests_properties(test_client_null_args PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;89;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_util_branches "/home/user/axiam-c-sdk/build-asan/tests/test_util_branches")
set_tests_properties(test_util_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;90;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_json_build "/home/user/axiam-c-sdk/build-asan/tests/test_json_build")
set_tests_properties(test_json_build PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;91;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_rule9_binding "/home/user/axiam-c-sdk/build-asan/tests/test_rule9_binding")
set_tests_properties(test_rule9_binding PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;94;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_jwks "/home/user/axiam-c-sdk/build-asan/tests/test_jwks")
set_tests_properties(test_jwks PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;102;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_revocation "/home/user/axiam-c-sdk/build-asan/tests/test_revocation")
set_tests_properties(test_revocation PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;112;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_guard "/home/user/axiam-c-sdk/build-asan/tests/test_guard")
set_tests_properties(test_guard PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;120;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_jwt_claims "/home/user/axiam-c-sdk/build-asan/tests/test_jwt_claims")
set_tests_properties(test_jwt_claims PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;130;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_reason_code "/home/user/axiam-c-sdk/build-asan/tests/test_reason_code")
set_tests_properties(test_reason_code PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;140;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_uma_challenge "/home/user/axiam-c-sdk/build-asan/tests/test_uma_challenge")
set_tests_properties(test_uma_challenge PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;149;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_guard_branches "/home/user/axiam-c-sdk/build-asan/tests/test_guard_branches")
set_tests_properties(test_guard_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;158;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_jwks_branches "/home/user/axiam-c-sdk/build-asan/tests/test_jwks_branches")
set_tests_properties(test_jwks_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;166;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(gen_pki "/usr/bin/cmake" "-E" "env" "sh" "/home/user/axiam-c-sdk/tests/gen_pki.sh" "/home/user/axiam-c-sdk/build-asan/tests/pki")
set_tests_properties(gen_pki PROPERTIES  FIXTURES_SETUP "AXIAM_PKI" _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;170;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_mtls "/home/user/axiam-c-sdk/build-asan/tests/test_mtls" "/home/user/axiam-c-sdk/build-asan/tests/pki")
set_tests_properties(test_mtls PROPERTIES  FIXTURES_REQUIRED "AXIAM_PKI" _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;181;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_transport_curl_extra "/home/user/axiam-c-sdk/build-asan/tests/test_transport_curl_extra" "/home/user/axiam-c-sdk/build-asan/tests/pki")
set_tests_properties(test_transport_curl_extra PROPERTIES  FIXTURES_REQUIRED "AXIAM_PKI" _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;192;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_tls_server "/home/user/axiam-c-sdk/build-asan/tests/test_tls_server" "/home/user/axiam-c-sdk/build-asan/tests/pki")
set_tests_properties(test_tls_server PROPERTIES  FIXTURES_REQUIRED "AXIAM_PKI" _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;206;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc "/home/user/axiam-c-sdk/build-asan/tests/test_oidc")
set_tests_properties(test_oidc PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;215;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_mtls_endpoint_aliases "/home/user/axiam-c-sdk/build-asan/tests/test_mtls_endpoint_aliases")
set_tests_properties(test_mtls_endpoint_aliases PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;216;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_login_providers "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_login_providers")
set_tests_properties(test_oidc_login_providers PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;217;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_idtoken "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_idtoken")
set_tests_properties(test_oidc_idtoken PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;226;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_logout "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_logout")
set_tests_properties(test_oidc_logout PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;234;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_grants "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_grants")
set_tests_properties(test_oidc_grants PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;236;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_singleflight "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_singleflight")
set_tests_properties(test_oidc_singleflight PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;246;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_branches "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_branches")
set_tests_properties(test_oidc_branches PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;249;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_shapes "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_shapes")
set_tests_properties(test_oidc_shapes PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;259;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_wire "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_wire")
set_tests_properties(test_oidc_wire PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;263;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_alloc_failures "/home/user/axiam-c-sdk/build-asan/tests/test_alloc_failures")
set_tests_properties(test_alloc_failures PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;284;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_webauthn "/home/user/axiam-c-sdk/build-asan/tests/test_webauthn")
set_tests_properties(test_webauthn PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;293;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_account "/home/user/axiam-c-sdk/build-asan/tests/test_account")
set_tests_properties(test_account PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;294;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_oidc_par "/home/user/axiam-c-sdk/build-asan/tests/test_oidc_par")
set_tests_properties(test_oidc_par PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;295;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_reactor "/home/user/axiam-c-sdk/build-asan/tests/test_reactor")
set_tests_properties(test_reactor PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;312;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_management_generated "/home/user/axiam-c-sdk/build-asan/tests/test_management_generated")
set_tests_properties(test_management_generated PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;317;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_management_semantics "/home/user/axiam-c-sdk/build-asan/tests/test_management_semantics")
set_tests_properties(test_management_semantics PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;318;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_contract_135 "/home/user/axiam-c-sdk/build-asan/tests/test_contract_135")
set_tests_properties(test_contract_135 PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;323;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_management_manifest "/home/user/axiam-c-sdk/build-asan/tests/test_management_manifest")
set_tests_properties(test_management_manifest PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;324;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_management_models_generated "/home/user/axiam-c-sdk/build-asan/tests/test_management_models_generated")
set_tests_properties(test_management_models_generated PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;27;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;325;axiam_add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
add_test(test_management_alloc_generated "/home/user/axiam-c-sdk/build-asan/tests/test_management_alloc_generated")
set_tests_properties(test_management_alloc_generated PROPERTIES  _BACKTRACE_TRIPLES "/home/user/axiam-c-sdk/tests/CMakeLists.txt;338;add_test;/home/user/axiam-c-sdk/tests/CMakeLists.txt;0;")
