/*
 * Contract 1.59 (CONTRACT.md §34) — the documentation rows, pinned against the text a
 * consumer actually reads: the public headers (generated by scripts/gen_management.py)
 * and the README.
 *
 * - R-29 (§31.3 rule 2): "An SDK MUST document the rule at both call sites" — the
 *   credential is bound to its URL, on `scim_targets.create` as well as `update`.
 * - R-29 (§29.3 rule 2): "an ECDSA certificate verifies HTTP-POST requests only; the
 *   HTTP-Redirect binding is RSA-only, and an SDK MUST say so where it documents the
 *   field" — on `sp_signing_cert_pem` itself, not only on the operations.
 * - R-41 (§21.9): the README's reason for declining DPoP must not be one the SDK's own
 *   §33.2 signer contradicts.
 *
 * A doc comment is "at" a declaration when it is the block comment that immediately
 * precedes it.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "unity.h"

static char *slurp(const char *rel) {
    char path[1024];
    snprintf(path, sizeof path, "%s/%s", AXIAM_REPO_ROOT, rel);
    FILE *f = fopen(path, "rb");
    TEST_ASSERT_NOT_NULL_MESSAGE(f, path);
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t) n + 1);
    TEST_ASSERT_NOT_NULL(buf);
    TEST_ASSERT_EQUAL_INT((int) n, (int) fread(buf, 1, (size_t) n, f));
    buf[n] = '\0';
    fclose(f);
    return buf;
}

/* The block comment immediately before `at` (whitespace between allowed), as a new
 * string; fails when there is none. */
static char *doc_before(const char *text, const char *at) {
    const char *p = at;
    while (p > text && (p[-1] == ' ' || p[-1] == '\n' || p[-1] == '\t')) p--;
    TEST_ASSERT_TRUE_MESSAGE(p - text >= 2 && p[-1] == '/' && p[-2] == '*',
                             "no doc comment directly before the declaration");
    const char *end = p;
    const char *start = end - 2;
    while (start > text && !(start[0] == '/' && start[1] == '*')) start--;
    size_t n = (size_t) (end - start);
    char *out = malloc(n + 1);
    TEST_ASSERT_NOT_NULL(out);
    memcpy(out, start, n);
    out[n] = '\0';
    /* Join the comment's lines so a phrase may wrap: drop "\n *" continuations. */
    char *w = out;
    for (const char *r = out; *r;) {
        if (*r == '\n') {
            r++;
            while (*r == ' ' || *r == '\t') r++;
            if (*r == '*' && r[1] != '/') r++;
            *w++ = ' ';
            while (*r == ' ') r++;
            continue;
        }
        *w++ = *r++;
    }
    *w = '\0';
    return out;
}

static void assert_says(const char *doc, const char *phrase, const char *where) {
    char msg[256];
    snprintf(msg, sizeof msg, "%s does not say \"%s\"", where, phrase);
    TEST_ASSERT_NOT_NULL_MESSAGE(strstr(doc, phrase), msg);
}

/* ---- R-29: §31.3 rule 2 at both call sites ----------------------------------------- */

static void test_the_credential_url_binding_is_documented_on_create_and_update(void) {
    char *ops = slurp("include/axiam/management_ops.h");
    static const char *const decls[] = {
        "axiam_error_kind_t axiam_scim_targets_create(",
        "axiam_error_kind_t axiam_scim_targets_update(",
    };
    for (int i = 0; i < 2; i++) {
        const char *at = strstr(ops, decls[i]);
        TEST_ASSERT_NOT_NULL_MESSAGE(at, decls[i]);
        char *doc = doc_before(ops, at);
        assert_says(doc, "The credential is bound to its URL", decls[i]);
        assert_says(doc, "31.3 rule 2", decls[i]);
        assert_says(doc, "`auth.token_url`", decls[i]);
        assert_says(doc, "`auth.type`", decls[i]);
        assert_says(doc, "`base_url`", decls[i]);
        free(doc);
    }
    free(ops);
}

/* ---- R-29: §29.3 rule 2 where the field is documented ------------------------------ */

static void test_the_ecdsa_redirect_limit_is_documented_on_the_field(void) {
    char *models = slurp("include/axiam/management_models.h");
    static const char *const structs[] = {
        "struct axiam_mgmt_saml_service_provider_input {",
        "struct axiam_mgmt_saml_service_provider {",
    };
    for (int i = 0; i < 2; i++) {
        const char *s = strstr(models, structs[i]);
        TEST_ASSERT_NOT_NULL_MESSAGE(s, structs[i]);
        const char *end = strstr(s, "\n};");
        const char *field = strstr(s, "char *sp_signing_cert_pem;");
        TEST_ASSERT_TRUE_MESSAGE(field && field < end, structs[i]);
        char *doc = doc_before(models, field);
        assert_says(doc, "ECDSA certificate verifies HTTP-POST requests only", structs[i]);
        assert_says(doc, "HTTP-Redirect binding is RSA-only", structs[i]);
        assert_says(doc, "29.3 rule 2", structs[i]);
        free(doc);
    }
    free(models);
}

/* ---- R-41: §21.9, the README's DPoP-decline reason --------------------------------- */

static void test_the_dpop_decline_reason_is_not_contradicted_by_the_ciba_signer(void) {
    char *readme = slurp("README.md");
    const char *start = strstr(readme, "### Sender-constrained tokens and DPoP");
    TEST_ASSERT_NOT_NULL(start);
    const char *end = strstr(start + 4, "\n### ");
    TEST_ASSERT_NOT_NULL(end);
    size_t n = (size_t) (end - start);
    char *section = malloc(n + 1);
    TEST_ASSERT_NOT_NULL(section);
    memcpy(section, start, n);
    section[n] = '\0';
    /* Join wrapped lines so a phrase may wrap. */
    for (char *p = section; *p; p++)
        if (*p == '\n') *p = ' ';
    /* The decline stands; the stated reason must be one the code does not contradict:
     * src/oidc_ciba.c signs PS256, ES256 and EdDSA with OpenSSL (§33.2). */
    assert_says(section, "deliberately declines §21.7.2 DPoP proof verification", "README");
    TEST_ASSERT_NULL_MESSAGE(strstr(section, "no JOSE implementation"),
                             "README still gives \"no JOSE implementation\" as the reason");
    assert_says(section, "§33.2", "README");
    free(section);
    free(readme);
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_the_credential_url_binding_is_documented_on_create_and_update);
    RUN_TEST(test_the_ecdsa_redirect_limit_is_documented_on_the_field);
    RUN_TEST(test_the_dpop_decline_reason_is_not_contradicted_by_the_ciba_signer);
    return UNITY_END();
}

void setUp(void) {}
void tearDown(void) {}
