/*
 * Reactor — CONTRACT.md §22, run against the committed §22.13 reference vectors.
 *
 * The vectors are generated by the AXIAM server's own sign path, so these are not
 * "does my implementation agree with itself" tests: a byte out of place in the
 * canonical form produces a MAC that differs from a number the server computed,
 * and the test says so.
 *
 * THE THREE PLACES A §22 PORT ACTUALLY BREAKS, all covered below:
 *
 *  1. `hmac_signature` is serialized as **null** INSIDE the signed bytes, not
 *     omitted as §8's own two message types omit it. A JSON library will drop or
 *     reorder that null, which is why both canonical forms are built by hand.
 *  2. `reason`, `patch` and `require_mfa` are OMITTED when absent or false. A
 *     reply that serializes `"require_mfa": false` produces different bytes and
 *     therefore a different MAC — reproduce the omission rule, not the values.
 *  3. Freshness is two-sided. A future timestamp is not "extra fresh"; it is the
 *     shape of a captured message held for later.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <openssl/hmac.h>

#include "unity.h"
#include "cJSON.h"
#include "axiam/axiam.h"
#include "axiam/reactor.h"
#include "internal.h"

#ifndef AXIAM_REACTOR_VECTORS
#define AXIAM_REACTOR_VECTORS "tests/reactor_v2_reference_vectors.json"
#endif

static cJSON *g_vectors;

static cJSON *vec(const char *a, const char *b) {
    cJSON *node = cJSON_GetObjectItemCaseSensitive(g_vectors, a);
    return b ? cJSON_GetObjectItemCaseSensitive(node, b) : node;
}

static const char *vec_str(cJSON *node, const char *key) {
    cJSON *v = cJSON_GetObjectItemCaseSensitive(node, key);
    return cJSON_IsString(v) ? v->valuestring : NULL;
}

/*
 * The tenant's derived AMQP subkey (§8.1) as RAW BYTES — the vectors publish it
 * in hex, and signing the hex string instead of the bytes is a MAC that will
 * never verify against anything the server produced.
 */
static axiam_sensitive_t *signing_key(void) {
    const char *hex = vec_str(vec("hkdf", NULL), "derived_subkey_hex");
    size_t n = strlen(hex) / 2;
    unsigned char *raw = malloc(n);
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        sscanf(hex + i * 2, "%2x", &v);
        raw[i] = (unsigned char)v;
    }
    axiam_sensitive_t *key = axiam_sensitive_new_bytes(raw, n);
    free(raw);
    return key;
}

static const char *tenant_id(void) { return vec_str(g_vectors, "tenant_id"); }
static const char *correlation_id(void) { return vec_str(g_vectors, "expected_correlation_id"); }

/* The instant the vectors were signed, so freshness passes deterministically. A
 * suite that used the real clock would start failing on a date nobody chose. */
static long verified_at(void) {
    struct tm tm;
    memset(&tm, 0, sizeof(tm));
    strptime(vec_str(g_vectors, "verified_at"), "%Y-%m-%dT%H:%M:%SZ", &tm);
    return (long)timegm(&tm);
}

/* The wire body: the committed message, printed compactly. */
static char *wire_body(cJSON *vector) {
    return cJSON_PrintUnformatted(cJSON_GetObjectItemCaseSensitive(vector, "message"));
}

/*
 * Sign an event body the way the SERVER does, so a test can build a validly
 * signed variant and isolate one defect at a time.
 *
 * Written out longhand rather than borrowed from the SDK on purpose: a test that
 * signed through the code under test could not tell a canonical-form bug from
 * agreement with itself. What proves this signer right is that the committed
 * vectors reproduce under it — asserted below.
 */
static char *sign_event(cJSON *message) {
    char *payload = cJSON_PrintUnformatted(
        cJSON_GetObjectItemCaseSensitive(message, "payload"));
    char canonical[4096];
    snprintf(canonical, sizeof(canonical),
             "{\"tenant_id\":\"%s\",\"event\":\"%s\",\"correlation_id\":\"%s\",\"payload\":%s,"
             "\"timeout_ms\":%lld,\"key_version\":%lld,\"nonce\":\"%s\",\"issued_at\":\"%s\","
             "\"hmac_signature\":null}",
             vec_str(message, "tenant_id"), vec_str(message, "event"),
             vec_str(message, "correlation_id"), payload,
             (long long)cJSON_GetObjectItemCaseSensitive(message, "timeout_ms")->valuedouble,
             (long long)cJSON_GetObjectItemCaseSensitive(message, "key_version")->valuedouble,
             vec_str(message, "nonce"), vec_str(message, "issued_at"));
    free(payload);

    axiam_sensitive_t *key = signing_key();
    unsigned char mac[EVP_MAX_MD_SIZE];
    unsigned int len = 0;
    HMAC(EVP_sha256(), axiam_sensitive_bytes(key), (int)axiam_sensitive_len(key),
         (const unsigned char *)canonical, strlen(canonical), mac, &len);
    axiam_sensitive_free(key);

    char hex[EVP_MAX_MD_SIZE * 2 + 1];
    for (unsigned int i = 0; i < len; i++) snprintf(hex + i * 2, 3, "%02x", mac[i]);

    cJSON *copy = cJSON_Duplicate(message, 1);
    cJSON_DeleteItemFromObjectCaseSensitive(copy, "hmac_signature");
    cJSON_AddStringToObject(copy, "hmac_signature", hex);
    char *body = cJSON_PrintUnformatted(copy);
    cJSON_Delete(copy);
    return body;
}

/* The committed event vector, re-stamped and re-signed. */
static char *event_at(const char *issued_at, const char *nonce) {
    cJSON *message = cJSON_Duplicate(
        cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"), "message"),
        1);
    cJSON_DeleteItemFromObjectCaseSensitive(message, "issued_at");
    cJSON_AddStringToObject(message, "issued_at", issued_at);
    if (nonce) {
        cJSON_DeleteItemFromObjectCaseSensitive(message, "nonce");
        cJSON_AddStringToObject(message, "nonce", nonce);
    }
    char *body = sign_event(message);
    cJSON_Delete(message);
    return body;
}

static void rfc3339_now(char *out, size_t n, long offset) {
    time_t t = time(NULL) + offset;
    struct tm tm;
    gmtime_r(&t, &tm);
    strftime(out, n, "%Y-%m-%dT%H:%M:%SZ", &tm);
}

/* ------------------------------------------------------------------ */
/* A transport that replays a script and records what was published    */
/* ------------------------------------------------------------------ */

#define MAX_SCRIPT 8

typedef struct {
    char *bodies[MAX_SCRIPT];
    const char *reply_to;
    int n_bodies;
    int at;
    int published;
    char last_destination[128];
    char last_correlation[128];
    char last_body[4096];
} script_t;

static int script_next(void *ctx, axiam_reactor_delivery_t *out) {
    script_t *s = ctx;
    if (s->at >= s->n_bodies) return 0;
    out->body = s->bodies[s->at++];
    out->reply_to = s->reply_to;
    out->correlation_id = NULL;
    return 1;
}

static void script_publish(void *ctx, const char *destination, const char *correlation_id,
                           const char *body) {
    script_t *s = ctx;
    s->published++;
    snprintf(s->last_destination, sizeof(s->last_destination), "%s", destination ? destination : "");
    snprintf(s->last_correlation, sizeof(s->last_correlation), "%s",
             correlation_id ? correlation_id : "");
    snprintf(s->last_body, sizeof(s->last_body), "%s", body ? body : "");
}

static void script_free(script_t *s) {
    for (int i = 0; i < s->n_bodies; i++) free(s->bodies[i]);
    memset(s, 0, sizeof(*s));
}

static axiam_reactor_transport_t script_transport(script_t *s) {
    axiam_reactor_transport_t t;
    t.ctx = s;
    t.next_delivery = script_next;
    t.publish_reply = script_publish;
    return t;
}

static long pinned_clock(void *ctx) {
    (void)ctx;
    return verified_at();
}

static const char *g_pinned_nonce = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";
static void pinned_nonce(void *ctx, char *out, size_t n) {
    (void)ctx;
    snprintf(out, n, "%s", g_pinned_nonce);
}

/* A config pinned to the vectors' own clock and nonce, so the sign direction is
 * reproducible byte-for-byte. Never how production is configured. */
static axiam_reactor_config_t pinned_config(const axiam_sensitive_t *key) {
    axiam_reactor_config_t config;
    memset(&config, 0, sizeof(config));
    config.tenant_id = tenant_id();
    config.reactor_id = vec_str(g_vectors, "reactor_id");
    config.signing_key = key;
    config.clock_fn = pinned_clock;
    config.nonce_fn = pinned_nonce;
    return config;
}

static axiam_reactor_decision_t always_allow(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    if (ctx) (*(int *)ctx)++;
    return axiam_reactor_allow();
}

static axiam_reactor_decision_t always_abstain(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    (void)ctx;
    return axiam_reactor_abstain();
}

static axiam_reactor_decision_t always_step_up(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    (void)ctx;
    return axiam_reactor_allow_with_step_up();
}

void setUp(void) {}
void tearDown(void) {}

/* ------------------------------------------------------------------ */
/* §22.13 sign direction                                              */
/* ------------------------------------------------------------------ */

static axiam_reactor_decision_t decision_from(cJSON *outcome,
                                              axiam_reactor_patch_entry_t *scratch,
                                              size_t *scratch_count) {
    const char *kind = vec_str(outcome, "kind");
    if (strcmp(kind, "deny") == 0) return axiam_reactor_deny(vec_str(outcome, "reason"));
    if (strcmp(kind, "mutate") == 0) {
        cJSON *patch = cJSON_GetObjectItemCaseSensitive(outcome, "patch");
        size_t n = 0;
        for (cJSON *e = patch->child; e; e = e->next) {
            scratch[n].key = e->string;
            scratch[n].value = e->valuestring;
            n++;
        }
        *scratch_count = n;
        return axiam_reactor_mutate(scratch, n);
    }
    /* The vectors spell the step-up answer as its own `kind`, which is exactly
     * the shape §22.4 says it is NOT: `require_mfa` rides on `allow` rather than
     * being a fourth decision value, and the canonical bytes show that. */
    if (strcmp(kind, "require_mfa") == 0) return axiam_reactor_allow_with_step_up();
    return axiam_reactor_allow();
}

void test_every_committed_reply_vector_reproduces_its_bytes_and_mac(void) {
    axiam_sensitive_t *key = signing_key();
    cJSON *replies = vec("reactor_to_server", NULL);
    for (cJSON *v = replies->child; v; v = v->next) {
        cJSON *message = cJSON_GetObjectItemCaseSensitive(v, "message");
        axiam_reactor_patch_entry_t scratch[8];
        size_t scratch_count = 0;
        axiam_reactor_decision_t decision =
            decision_from(cJSON_GetObjectItemCaseSensitive(v, "expected_outcome"), scratch,
                          &scratch_count);

        char *canonical = axiam_reactor_canonical_reply(
            correlation_id(), tenant_id(), vec_str(message, "event"), &decision,
            vec_str(message, "nonce"), vec_str(message, "issued_at"));
        TEST_ASSERT_NOT_NULL(canonical);
        TEST_ASSERT_EQUAL_STRING(vec_str(v, "canonical_signed_json"), canonical);
        free(canonical);

        char *wire = axiam_reactor_build_reply(key, correlation_id(), tenant_id(),
                                               vec_str(message, "event"), &decision,
                                               vec_str(message, "nonce"),
                                               vec_str(message, "issued_at"));
        TEST_ASSERT_NOT_NULL(wire);
        cJSON *parsed = cJSON_Parse(wire);
        TEST_ASSERT_EQUAL_STRING(vec_str(v, "hmac_signature_hex"),
                                 vec_str(parsed, "hmac_signature"));
        cJSON_Delete(parsed);
        free(wire);
    }
    axiam_sensitive_free(key);
}

void test_require_mfa_is_omitted_when_false(void) {
    /* The omission changes the canonical bytes and therefore the MAC. An
     * implementation that reproduces the values but not the omission rule passes
     * every "is the field right" assertion and fails every real reply. */
    axiam_reactor_decision_t allow = axiam_reactor_allow();
    char *plain = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &allow, "n",
                                                "2026-07-10T12:00:00Z");
    TEST_ASSERT_NULL(strstr(plain, "require_mfa"));
    free(plain);

    axiam_reactor_decision_t step_up = axiam_reactor_allow_with_step_up();
    char *with = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                               AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &step_up, "n",
                                               "2026-07-10T12:00:00Z");
    TEST_ASSERT_NOT_NULL(strstr(with, "\"require_mfa\":true"));
    free(with);
}

void test_reason_and_patch_are_omitted_when_absent(void) {
    axiam_reactor_decision_t allow = axiam_reactor_allow();
    char *a = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                            AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &allow, "n",
                                            "2026-07-10T12:00:00Z");
    TEST_ASSERT_NULL(strstr(a, "reason"));
    TEST_ASSERT_NULL(strstr(a, "patch"));
    free(a);

    /* A deny with no reason still denies; the server substitutes "denied by
     * reactor". An empty reason is omitted, not sent as "". */
    axiam_reactor_decision_t bare = axiam_reactor_deny("");
    char *d = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                            AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &bare, "n",
                                            "2026-07-10T12:00:00Z");
    TEST_ASSERT_NULL(strstr(d, "reason"));
    TEST_ASSERT_NOT_NULL(strstr(d, "\"decision\":\"deny\""));
    free(d);
}

void test_the_nonce_is_inside_the_signed_bytes(void) {
    /* Two replies differing only in `nonce` carry different MACs — the
     * nonce_binding vector pair, checked against the server's own numbers. The
     * pair is the `allow` reply with only its nonce changed. */
    axiam_sensitive_t *key = signing_key();
    cJSON *binding = vec("nonce_binding", NULL);
    axiam_reactor_decision_t allow = axiam_reactor_allow();

    char *a = axiam_reactor_build_reply(key, correlation_id(), tenant_id(),
                                        AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &allow,
                                        vec_str(binding, "nonce_a"), "2026-07-10T12:00:00Z");
    char *b = axiam_reactor_build_reply(key, correlation_id(), tenant_id(),
                                        AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &allow,
                                        vec_str(binding, "nonce_b"), "2026-07-10T12:00:00Z");
    cJSON *pa = cJSON_Parse(a);
    cJSON *pb = cJSON_Parse(b);
    TEST_ASSERT_EQUAL_STRING(vec_str(binding, "hmac_a_hex"), vec_str(pa, "hmac_signature"));
    TEST_ASSERT_EQUAL_STRING(vec_str(binding, "hmac_b_hex"), vec_str(pb, "hmac_signature"));
    TEST_ASSERT_NOT_EQUAL(0, strcmp(vec_str(pa, "hmac_signature"), vec_str(pb, "hmac_signature")));

    cJSON_Delete(pa);
    cJSON_Delete(pb);
    free(a);
    free(b);
    axiam_sensitive_free(key);
}

void test_a_mutate_never_becomes_allow_plus_patch(void) {
    axiam_reactor_patch_entry_t patch[1] = {{"ext.department", "eng"}};
    axiam_reactor_decision_t d = axiam_reactor_mutate(patch, 1);
    char *canonical = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                    AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &d, "n",
                                                    "2026-07-10T12:00:00Z");
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\"decision\":\"mutate\""));
    TEST_ASSERT_NULL(strstr(canonical, "\"decision\":\"allow\""));
    free(canonical);
}

void test_a_forbidden_patch_key_is_sent_unfiltered(void) {
    /* §22.4 rule 1 / §22.10 rule 3. One forbidden key rejects the WHOLE patch
     * server-side, including the fields that would have been fine — and dropping
     * the offender to rescue the rest would leave the author believing a field
     * was set when it was dropped. */
    axiam_reactor_patch_entry_t patch[2] = {{"ext.department", "eng"}, {"sub", "attacker"}};
    axiam_reactor_decision_t d = axiam_reactor_mutate(patch, 2);
    char *canonical = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                    AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &d, "n",
                                                    "2026-07-10T12:00:00Z");
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\"sub\":\"attacker\""));
    free(canonical);
    /* And the SDK knows perfectly well it is forbidden — it just does not act on
     * that knowledge when building the reply. */
    TEST_ASSERT_EQUAL_INT(
        0, axiam_reactor_patch_field_allowed(AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, "sub"));
}

void test_a_patch_is_emitted_in_byte_order(void) {
    /* The server's BTreeMap emits byte order; a patch left in call order would
     * produce a MAC that verifies only by luck. */
    axiam_reactor_patch_entry_t patch[3] = {
        {"ext.zulu", "z"}, {"ext.alpha", "a"}, {"ext.mike", "m"}};
    axiam_reactor_decision_t d = axiam_reactor_mutate(patch, 3);
    char *canonical = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                    AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &d, "n",
                                                    "2026-07-10T12:00:00Z");
    const char *alpha = strstr(canonical, "ext.alpha");
    const char *mike = strstr(canonical, "ext.mike");
    const char *zulu = strstr(canonical, "ext.zulu");
    TEST_ASSERT_TRUE(alpha < mike && mike < zulu);
    free(canonical);
}

void test_string_escaping_is_serde_jsons(void) {
    /* The two mandatory escapes, the five short forms, \u00XX for the remaining
     * control characters — and NOTHING else. A forward slash stays literal and
     * UTF-8 passes through unescaped, which is where a naive port diverges and
     * produces a MAC the server will not accept. */
    const char *reason = "a \"quoted\" \\ back\nline\ttab\r\b\f / slash \001 \xc3\xbcnicode";
    axiam_reactor_decision_t d = axiam_reactor_deny(reason);
    char *canonical = axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                    AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &d, "n",
                                                    "2026-07-10T12:00:00Z");
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\\"quoted\\\""));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\n"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\t"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\r"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\b"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\f"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\\u0001"));
    TEST_ASSERT_NULL(strstr(canonical, "\\/"));
    TEST_ASSERT_NOT_NULL(strstr(canonical, "\xc3\xbcnicode"));
    /* And it is still parseable JSON that round-trips to the same string. */
    cJSON *parsed = cJSON_Parse(canonical);
    TEST_ASSERT_EQUAL_STRING(reason, vec_str(parsed, "reason"));
    cJSON_Delete(parsed);
    free(canonical);
}

void test_require_mfa_on_any_other_event_is_refused(void) {
    /* Refused rather than corrected: the result is NO REPLY, and the
     * registration's failure_policy decides. */
    axiam_sensitive_t *key = signing_key();
    axiam_reactor_decision_t d = axiam_reactor_allow_with_step_up();
    TEST_ASSERT_NULL(axiam_reactor_build_reply(key, correlation_id(), tenant_id(),
                                               AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &d, "n",
                                               "2026-07-10T12:00:00Z"));
    axiam_sensitive_free(key);
}

void test_an_empty_mutate_is_refused(void) {
    axiam_sensitive_t *key = signing_key();
    axiam_reactor_decision_t d = axiam_reactor_mutate(NULL, 0);
    TEST_ASSERT_NULL(axiam_reactor_build_reply(key, correlation_id(), tenant_id(),
                                               AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, &d, "n",
                                               "2026-07-10T12:00:00Z"));
    axiam_sensitive_free(key);
}

void test_an_abstention_has_no_wire_form(void) {
    axiam_reactor_decision_t d = axiam_reactor_abstain();
    TEST_ASSERT_NULL(axiam_reactor_canonical_reply(correlation_id(), tenant_id(),
                                                   AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, &d, "n",
                                                   "2026-07-10T12:00:00Z"));
}

/* ------------------------------------------------------------------ */
/* §22.13 verify direction                                            */
/* ------------------------------------------------------------------ */

void test_the_test_signer_reproduces_the_committed_vectors(void) {
    /* The premise of every re-signed case below. If this fails, those tests are
     * agreeing with a bug rather than with the server. */
    cJSON *vector = vec("server_to_reactor", "login_post_auth");
    char *resigned = sign_event(cJSON_GetObjectItemCaseSensitive(vector, "message"));
    cJSON *parsed = cJSON_Parse(resigned);
    TEST_ASSERT_EQUAL_STRING(vec_str(vector, "hmac_signature_hex"),
                             vec_str(parsed, "hmac_signature"));
    cJSON_Delete(parsed);
    free(resigned);
}

void test_every_committed_event_vector_verifies(void) {
    axiam_sensitive_t *key = signing_key();
    cJSON *events = vec("server_to_reactor", NULL);
    for (cJSON *v = events->child; v; v = v->next) {
        char *body = wire_body(v);
        axiam_reactor_verified_t verified;
        TEST_ASSERT_EQUAL(AXIAM_REACTOR_OK,
                          axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                     &verified));
        TEST_ASSERT_EQUAL_STRING(
            vec_str(cJSON_GetObjectItemCaseSensitive(v, "message"), "event"),
            verified.event.event);
        TEST_ASSERT_EQUAL_STRING(correlation_id(), verified.event.correlation_id);
        axiam_reactor_verified_dispose(&verified);
        free(body);
    }
    axiam_sensitive_free(key);
}

void test_an_event_fails_under_any_other_key(void) {
    axiam_sensitive_t *other = axiam_sensitive_new_bytes("\x01\x02\x03\x04", 4);
    char *body = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_BAD_SIGNATURE,
                      axiam_reactor_verify_event(other, body, tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    axiam_sensitive_free(other);
}

void test_tampering_with_any_signed_field_invalidates_the_event(void) {
    axiam_sensitive_t *key = signing_key();
    const char *fields[] = {"payload", "timeout_ms", "tenant_id", "nonce"};
    for (int i = 0; i < 4; i++) {
        cJSON *message = cJSON_Duplicate(
            cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"),
                                             "message"),
            1);
        if (strcmp(fields[i], "timeout_ms") == 0) {
            cJSON_GetObjectItemCaseSensitive(message, "timeout_ms")->valuedouble += 1;
        } else if (strcmp(fields[i], "payload") == 0) {
            cJSON *payload = cJSON_GetObjectItemCaseSensitive(message, "payload");
            cJSON_DeleteItemFromObjectCaseSensitive(payload, "sub");
            cJSON_AddStringToObject(payload, "sub", "mallory");
        } else {
            cJSON_DeleteItemFromObjectCaseSensitive(message, fields[i]);
            cJSON_AddStringToObject(message, fields[i], "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
        }
        char *body = cJSON_PrintUnformatted(message);
        axiam_reactor_verified_t verified;
        TEST_ASSERT_EQUAL(AXIAM_REACTOR_BAD_SIGNATURE,
                          axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                     &verified));
        axiam_reactor_verified_dispose(&verified);
        free(body);
        cJSON_Delete(message);
    }
    axiam_sensitive_free(key);
}

void test_key_version_below_two_is_refused_before_the_signature(void) {
    axiam_sensitive_t *key = signing_key();
    cJSON *message = cJSON_Duplicate(
        cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"), "message"),
        1);
    cJSON_GetObjectItemCaseSensitive(message, "key_version")->valuedouble = 1;
    char *body = cJSON_PrintUnformatted(message);

    axiam_reactor_verified_t verified;
    /* Not BAD_SIGNATURE: the version check comes first, and reporting it as a
     * signature failure would send an operator looking at the wrong key. */
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_KEY_VERSION_TOO_OLD,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    cJSON_Delete(message);
    axiam_sensitive_free(key);
}

void test_freshness_is_refused_in_both_directions(void) {
    axiam_sensitive_t *key = signing_key();
    char *body = wire_body(vec("server_to_reactor", "login_post_auth"));
    long skew = (long)cJSON_GetObjectItemCaseSensitive(g_vectors, "freshness_skew_secs")
                    ->valuedouble;
    axiam_reactor_verified_t verified;

    TEST_ASSERT_EQUAL(AXIAM_REACTOR_STALE,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at() + skew + 1,
                                                 NULL, &verified));
    axiam_reactor_verified_dispose(&verified);

    /* A future timestamp is not "extra fresh" — it is the shape of a captured
     * message held for later. */
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_STALE,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at() - skew - 1,
                                                 NULL, &verified));
    axiam_reactor_verified_dispose(&verified);

    /* And the boundary itself is inside the window. */
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_OK,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at() + skew,
                                                 NULL, &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    axiam_sensitive_free(key);
}

void test_a_repeated_nonce_is_refused_as_a_replay(void) {
    axiam_sensitive_t *key = signing_key();
    char *body = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_nonce_set_t *seen = axiam_reactor_nonce_set_new();
    axiam_reactor_verified_t verified;

    TEST_ASSERT_EQUAL(AXIAM_REACTOR_OK, axiam_reactor_verify_event(key, body, tenant_id(),
                                                                   verified_at(), seen,
                                                                   &verified));
    axiam_reactor_verified_dispose(&verified);
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_REPLAY, axiam_reactor_verify_event(key, body, tenant_id(),
                                                                       verified_at(), seen,
                                                                       &verified));
    axiam_reactor_verified_dispose(&verified);

    axiam_reactor_nonce_set_free(seen);
    free(body);
    axiam_sensitive_free(key);
}

void test_an_event_for_another_tenant_is_refused_after_the_mac(void) {
    axiam_sensitive_t *key = signing_key();
    char *body = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_TENANT_MISMATCH,
                      axiam_reactor_verify_event(key, body, "99999999-9999-9999-9999-999999999999",
                                                 verified_at(), NULL, &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    axiam_sensitive_free(key);
}

void test_an_unregistered_operation_is_refused_after_the_mac(void) {
    /* Also how §22.7's exclusion refuses: those operations are in no registry, so
     * a delivery naming one never reaches a handler. Validly signed, so the
     * registry check is what actually fires. */
    axiam_sensitive_t *key = signing_key();
    cJSON *message = cJSON_Duplicate(
        cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"), "message"),
        1);
    cJSON_DeleteItemFromObjectCaseSensitive(message, "event");
    cJSON_AddStringToObject(message, "event", "authz.check");
    char *body = sign_event(message);

    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_UNKNOWN_EVENT,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    cJSON_Delete(message);
    axiam_sensitive_free(key);
}

void test_an_unparseable_issued_at_is_malformed_not_stale(void) {
    /* Validly signed, so the MAC is not the defect — a body that got past the MAC
     * and still carries a timestamp nobody can read is malformed, not late, and
     * saying "stale" would send an operator to check clock drift. */
    axiam_sensitive_t *key = signing_key();
    char *body = event_at("yesterday", NULL);
    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_MALFORMED,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    axiam_sensitive_free(key);
}

void test_a_body_missing_a_signed_field_is_malformed(void) {
    axiam_sensitive_t *key = signing_key();
    const char *fields[] = {"tenant_id", "event", "correlation_id", "payload", "timeout_ms",
                            "nonce", "issued_at"};
    for (int i = 0; i < 7; i++) {
        cJSON *message = cJSON_Duplicate(
            cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"),
                                             "message"),
            1);
        cJSON_DeleteItemFromObjectCaseSensitive(message, fields[i]);
        char *body = cJSON_PrintUnformatted(message);
        axiam_reactor_verified_t verified;
        TEST_ASSERT_EQUAL(AXIAM_REACTOR_MALFORMED,
                          axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                     &verified));
        axiam_reactor_verified_dispose(&verified);
        free(body);
        cJSON_Delete(message);
    }
    axiam_sensitive_free(key);
}

void test_a_body_that_is_not_json_is_malformed(void) {
    axiam_sensitive_t *key = signing_key();
    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_MALFORMED,
                      axiam_reactor_verify_event(key, "<html>", tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_MALFORMED,
                      axiam_reactor_verify_event(NULL, "{}", tenant_id(), 0, NULL, &verified));
    axiam_reactor_verified_dispose(&verified);
    axiam_sensitive_free(key);
}

void test_an_event_with_no_signature_at_all_is_refused(void) {
    axiam_sensitive_t *key = signing_key();
    cJSON *message = cJSON_Duplicate(
        cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"), "message"),
        1);
    cJSON_DeleteItemFromObjectCaseSensitive(message, "hmac_signature");
    char *body = cJSON_PrintUnformatted(message);
    axiam_reactor_verified_t verified;
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_BAD_SIGNATURE,
                      axiam_reactor_verify_event(key, body, tenant_id(), verified_at(), NULL,
                                                 &verified));
    axiam_reactor_verified_dispose(&verified);
    free(body);
    cJSON_Delete(message);
    axiam_sensitive_free(key);
}

void test_the_correlation_replay_vector_does_not_transfer(void) {
    /* The accepted reply verbatim — valid signature, inside the freshness window
     * — presented against a different in-flight event. The correlation_id is
     * inside the signed bytes, so re-signing for the other event is what an
     * attacker cannot do. */
    axiam_sensitive_t *key = signing_key();
    cJSON *replay = vec("rejected_replies", "correlation_replay");
    cJSON *message = cJSON_GetObjectItemCaseSensitive(replay, "message");
    axiam_reactor_decision_t allow = axiam_reactor_allow();

    char *for_other = axiam_reactor_build_reply(
        key, vec_str(replay, "verify_against_correlation_id"), tenant_id(),
        vec_str(message, "event"), &allow, vec_str(message, "nonce"),
        vec_str(message, "issued_at"));
    cJSON *parsed = cJSON_Parse(for_other);
    TEST_ASSERT_NOT_EQUAL(0, strcmp(vec_str(replay, "hmac_signature_hex"),
                                    vec_str(parsed, "hmac_signature")));
    cJSON_Delete(parsed);
    free(for_other);
    axiam_sensitive_free(key);
}

/* ------------------------------------------------------------------ */
/* §22.5 the registry and its allow-lists                             */
/* ------------------------------------------------------------------ */

void test_token_pre_issue_admits_the_ext_namespace_and_nothing_else(void) {
    const char *e = AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE;
    TEST_ASSERT_EQUAL_INT(1, axiam_reactor_patch_field_allowed(e, "ext.department"));
    TEST_ASSERT_EQUAL_INT(1, axiam_reactor_patch_field_allowed(e, "ext.a.b.c"));
    /* `ext.` names the namespace, not a claim. */
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "ext."));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "ext"));
    /* A prefix match on the string is not a match on the namespace. */
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "extra"));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "external_id"));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "evil.ext.department"));
    /* Every standard claim, because none begins with `ext.` — which is the whole
     * design: a hook that could rewrite `sub` could mint a token for anyone. */
    const char *claims[] = {"sub", "aud", "exp", "iat", "iss", "scope", "tenant_id"};
    for (int i = 0; i < 7; i++) {
        TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, claims[i]));
    }
}

void test_user_pre_create_admits_its_fields_and_its_namespace(void) {
    const char *e = AXIAM_REACTOR_EVENT_USER_PRE_CREATE;
    TEST_ASSERT_EQUAL_INT(1, axiam_reactor_patch_field_allowed(e, "email"));
    TEST_ASSERT_EQUAL_INT(1, axiam_reactor_patch_field_allowed(e, "username"));
    TEST_ASSERT_EQUAL_INT(1, axiam_reactor_patch_field_allowed(e, "metadata.source"));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "metadata")); /* bare namespace */
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "password"));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "tenant_id"));
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(e, "roles"));
}

void test_the_veto_only_events_accept_no_patch_field(void) {
    const char *events[] = {AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH,
                            AXIAM_REACTOR_EVENT_GRANT_PRE_ASSIGN};
    const char *fields[] = {"email", "ext.department", "metadata.source", "anything"};
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 4; j++) {
            TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed(events[i], fields[j]));
        }
    }
    /* And an event that is in no registry at all admits nothing either. */
    TEST_ASSERT_EQUAL_INT(0, axiam_reactor_patch_field_allowed("authz.check", "anything"));
}

void test_the_hot_path_operations_are_absent_from_every_exposed_constant(void) {
    /* §22.7 is a normative MUST NOT, and §22.13 says to assert on the list rather
     * than on a comment. A reactor round trip is milliseconds; the check path's
     * budget is microseconds. */
    size_t count = 0;
    const char *const *names = axiam_reactor_event_names(&count);
    TEST_ASSERT_EQUAL_size_t(5, count);
    for (size_t i = 0; i < count; i++) {
        TEST_ASSERT_NOT_EQUAL(0, strcmp(names[i], "authz.check"));
        TEST_ASSERT_NOT_EQUAL(0, strcmp(names[i], "authz.check_batch"));
        TEST_ASSERT_NOT_EQUAL(0, strcmp(names[i], "token.introspect"));
    }
}

void test_the_strictest_default_wins_in_either_order(void) {
    const char *open_only[] = {AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE};
    const char *closed_only[] = {AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH};
    const char *both[] = {AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE,
                          AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH};
    const char *reversed[] = {AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH,
                              AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE};

    TEST_ASSERT_EQUAL_STRING("fail_open", axiam_reactor_default_failure_policy(open_only, 1));
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(closed_only, 1));
    /* Both orders, because reducing this to "take the first event's default"
     * would let the order of a JSON array decide whether an unreachable fraud
     * check passes. */
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(both, 2));
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(reversed, 2));
    /* An empty or unrecognised registration is not "nothing to fail at". */
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(NULL, 0));
    const char *unknown[] = {"authz.check"};
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(unknown, 1));
}

void test_the_topology_names_match_the_vectors(void) {
    cJSON *topology = vec("topology", NULL);
    char *queue = axiam_reactor_queue_name(tenant_id(), vec_str(g_vectors, "reactor_id"));
    TEST_ASSERT_EQUAL_STRING(vec_str(topology, "queue"), queue);
    free(queue);

    char *key = axiam_reactor_routing_key(tenant_id(), AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH);
    TEST_ASSERT_EQUAL_STRING(vec_str(topology, "routing_key_login_post_auth"), key);
    free(key);

    TEST_ASSERT_NULL(axiam_reactor_queue_name(NULL, "r"));
    TEST_ASSERT_NULL(axiam_reactor_routing_key("t", NULL));
}

/* ------------------------------------------------------------------ */
/* §22.10 the runtime                                                 */
/* ------------------------------------------------------------------ */

void test_the_runtime_verifies_dispatches_and_publishes(void) {
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "login_post_auth"));
    s.reply_to = "amq.rabbitmq.reply-to.abc";
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    int dispatches = 0;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_reactor_serve(&config, &transport, always_allow, &dispatches, &err));
    TEST_ASSERT_EQUAL_INT(1, dispatches);
    TEST_ASSERT_EQUAL_INT(1, s.published);
    TEST_ASSERT_EQUAL_STRING("amq.rabbitmq.reply-to.abc", s.last_destination);
    TEST_ASSERT_EQUAL_STRING(correlation_id(), s.last_correlation);

    cJSON *reply = cJSON_Parse(s.last_body);
    TEST_ASSERT_EQUAL_STRING("allow", vec_str(reply, "decision"));
    TEST_ASSERT_NOT_NULL(vec_str(reply, "hmac_signature"));
    cJSON_Delete(reply);

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_an_unverifiable_delivery_produces_no_reply(void) {
    axiam_sensitive_t *key = signing_key();
    cJSON *message = cJSON_Duplicate(
        cJSON_GetObjectItemCaseSensitive(vec("server_to_reactor", "login_post_auth"), "message"),
        1);
    cJSON *payload = cJSON_GetObjectItemCaseSensitive(message, "payload");
    cJSON_DeleteItemFromObjectCaseSensitive(payload, "sub");
    cJSON_AddStringToObject(payload, "sub", "mallory");

    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = cJSON_PrintUnformatted(message);
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    int dispatches = 0;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_reactor_serve(&config, &transport, always_allow, &dispatches, &err));
    /* And the handler never saw it: a runtime that hands unverified bytes to user
     * code has already lost, because the handler will act on them. */
    TEST_ASSERT_EQUAL_INT(0, dispatches);
    TEST_ASSERT_EQUAL_INT(0, s.published);

    script_free(&s);
    cJSON_Delete(message);
    axiam_sensitive_free(key);
}

void test_an_abstaining_handler_produces_no_reply(void) {
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_reactor_serve(&config, &transport, always_abstain, NULL, &err));
    TEST_ASSERT_EQUAL_INT(0, s.published);

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_a_reply_the_builder_refuses_produces_no_reply(void) {
    /* require_mfa on token.pre_issue. The runtime's own error, and §22.10 rule 2
     * applies to it exactly as to a handler that failed. */
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "token_pre_issue"));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_reactor_serve(&config, &transport, always_step_up, NULL, &err));
    TEST_ASSERT_EQUAL_INT(0, s.published);

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_the_runtime_keeps_one_nonce_set_for_its_whole_lifetime(void) {
    /* Building a fresh set per delivery defeats replay dedup entirely, and the
     * only way to see the difference is to feed the same delivery twice. */
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "login_post_auth"));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    int dispatches = 0;
    axiam_error_t err;
    axiam_reactor_serve(&config, &transport, always_allow, &dispatches, &err);
    TEST_ASSERT_EQUAL_INT(1, dispatches);
    TEST_ASSERT_EQUAL_INT(1, s.published);

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_two_deliveries_with_different_nonces_both_dispatch(void) {
    /* The complement of the replay test: the seen-set must not turn every second
     * delivery away, which is what a set keyed on something other than the nonce
     * would do. */
    axiam_sensitive_t *key = signing_key();
    char now[32];
    rfc3339_now(now, sizeof(now), 0);

    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = event_at(now, "11111111-1111-1111-1111-111111111111");
    s.bodies[s.n_bodies++] = event_at(now, "22222222-2222-2222-2222-222222222222");
    axiam_reactor_transport_t transport = script_transport(&s);

    /* And with the REAL clock and nonce source: the seams exist for §22.13's
     * pinned vectors, and a config that sets neither must still work. */
    axiam_reactor_config_t config;
    memset(&config, 0, sizeof(config));
    config.tenant_id = tenant_id();
    config.signing_key = key;

    int dispatches = 0;
    axiam_error_t err;
    axiam_reactor_serve(&config, &transport, always_allow, &dispatches, &err);
    TEST_ASSERT_EQUAL_INT(2, dispatches);
    TEST_ASSERT_EQUAL_INT(2, s.published);

    cJSON *reply = cJSON_Parse(s.last_body);
    /* A real nonce: 36 characters of UUID, and not the fixture's. */
    TEST_ASSERT_EQUAL_size_t(36, strlen(vec_str(reply, "nonce")));
    TEST_ASSERT_NOT_EQUAL(0, strcmp(vec_str(reply, "nonce"), g_pinned_nonce));
    TEST_ASSERT_EQUAL_size_t(20, strlen(vec_str(reply, "issued_at")));
    cJSON_Delete(reply);

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_the_reply_never_carries_the_signing_key(void) {
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "login_post_auth"));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);

    axiam_error_t err;
    axiam_reactor_serve(&config, &transport, always_allow, NULL, &err);
    TEST_ASSERT_EQUAL_INT(1, s.published);
    TEST_ASSERT_NULL(strstr(s.last_body, vec_str(vec("hkdf", NULL), "derived_subkey_hex")));

    /* §22.12: the tenant AMQP signing key is a credential, exactly as §8's key
     * already is. It must not appear at any log level, nor in a reconnect
     * diagnostic. */
    TEST_ASSERT_EQUAL_STRING("[SENSITIVE]", axiam_sensitive_to_string(key));

    script_free(&s);
    axiam_sensitive_free(key);
}

void test_serve_refuses_a_missing_handler_config_or_tenant(void) {
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);
    axiam_error_t err;

    TEST_ASSERT_NOT_EQUAL(AXIAM_OK,
                          axiam_reactor_serve(&config, &transport, NULL, NULL, &err));
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK,
                          axiam_reactor_serve(NULL, &transport, always_allow, NULL, &err));
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK, axiam_reactor_serve(&config, NULL, always_allow, NULL, &err));

    config.tenant_id = NULL;
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                      axiam_reactor_serve(&config, &transport, always_allow, NULL, &err));
    config.tenant_id = tenant_id();
    config.signing_key = NULL;
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                      axiam_reactor_serve(&config, &transport, always_allow, NULL, &err));

    axiam_sensitive_free(key);
}

/* ------------------------------------------------------------------ */
/* §22.14.1 the binder                                                */
/* ------------------------------------------------------------------ */

static axiam_reactor_decision_t mark_login(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    snprintf((char *)ctx, 16, "login");
    return axiam_reactor_allow();
}
static axiam_reactor_decision_t mark_token(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    snprintf((char *)ctx, 16, "token");
    return axiam_reactor_allow();
}
static axiam_reactor_decision_t deny_fallback(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    if (ctx) *(int *)ctx = 1;
    return axiam_reactor_deny("unhandled by this reactor");
}
static axiam_reactor_decision_t leak_patch(const axiam_reactor_event_t *e, void *ctx) {
    (void)e;
    (void)ctx;
    static axiam_reactor_patch_entry_t patch[2] = {{"ext.department", "eng"},
                                                   {"sub", "attacker"}};
    return axiam_reactor_mutate(patch, 2);
}

void test_router_two_events_reach_their_own_handlers(void) {
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    char reached[16] = {0};
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_reactor_router_on(
                                    router, AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, mark_login,
                                    reached, &err));
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_reactor_router_on(
                                    router, AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, mark_token,
                                    reached, &err));

    axiam_reactor_handler_fn handler = axiam_reactor_router_handler();
    axiam_reactor_event_t event;
    memset(&event, 0, sizeof(event));

    event.event = AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH;
    handler(&event, router);
    TEST_ASSERT_EQUAL_STRING("login", reached);

    event.event = AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE;
    handler(&event, router);
    TEST_ASSERT_EQUAL_STRING("token", reached);

    axiam_reactor_router_free(router);
}

void test_router_a_name_outside_the_registry_is_refused_at_bind_time(void) {
    /* Rule 2. Failing when the binding is written is the entire point: a typo
     * that survives to production is discovered as silence, and silence on a
     * fail_open event is indistinguishable from a healthy reactor with nothing to
     * say. */
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                      axiam_reactor_router_on(router, "login.postauth", mark_login, NULL, &err));
    TEST_ASSERT_NOT_NULL(strstr(err.message, "§22.5"));
    axiam_reactor_router_free(router);
}

void test_router_a_hot_path_operation_is_refused_like_any_unknown_name(void) {
    /* §22.7's three are in no registry row, so they fail rule 2 exactly as a typo
     * does — and the message names the registry rather than naming what is absent
     * from it. A separate hot-path list would be a constant naming them, which
     * §22.13's hot-path assertion forbids outright. */
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    const char *hot[] = {"authz.check", "authz.check_batch", "token.introspect"};
    axiam_error_t err;
    for (int i = 0; i < 3; i++) {
        TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                          axiam_reactor_router_on(router, hot[i], mark_login, NULL, &err));
        TEST_ASSERT_NOT_NULL(strstr(err.message, "§22.5"));
        TEST_ASSERT_NULL(strstr(err.message, "hot"));
    }
    axiam_reactor_router_free(router);
}

void test_router_a_second_binding_is_an_error_not_an_overwrite(void) {
    /* Rule 3. Which of two handlers runs is not something the author of either
     * can see from their own file. */
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_reactor_router_on(
                                    router, AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, mark_login, NULL,
                                    &err));
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH, axiam_reactor_router_on(
                                          router, AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, mark_token,
                                          NULL, &err));
    TEST_ASSERT_NOT_NULL(strstr(err.message, "already has a handler"));
    axiam_reactor_router_free(router);
}

void test_router_an_unbound_event_abstains(void) {
    /* Rule 4, and the reason this subsection exists. It is not answered `allow`,
     * and not answered `deny` either: the binder does not know what the
     * registration was for, and the operator's policy does. */
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    axiam_error_t err;
    axiam_reactor_router_on(router, AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, mark_login, NULL, &err);

    axiam_reactor_event_t event;
    memset(&event, 0, sizeof(event));
    event.event = AXIAM_REACTOR_EVENT_USER_PRE_CREATE;
    axiam_reactor_decision_t answer = axiam_reactor_router_handler()(&event, router);
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_ABSTAIN, answer.kind);

    /* And through the runtime, where abstention means zero published messages. */
    axiam_sensitive_t *key = signing_key();
    script_t s;
    memset(&s, 0, sizeof(s));
    s.bodies[s.n_bodies++] = wire_body(vec("server_to_reactor", "token_pre_issue"));
    axiam_reactor_transport_t transport = script_transport(&s);
    axiam_reactor_config_t config = pinned_config(key);
    axiam_reactor_serve(&config, &transport, axiam_reactor_router_handler(), router, &err);
    TEST_ASSERT_EQUAL_INT(0, s.published);

    script_free(&s);
    axiam_sensitive_free(key);
    axiam_reactor_router_free(router);
}

void test_router_an_explicit_fallback_is_honoured_and_has_no_default(void) {
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    int fell_back = 0;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_reactor_router_fallback(router, deny_fallback, &fell_back, &err));

    axiam_reactor_event_t event;
    memset(&event, 0, sizeof(event));
    event.event = AXIAM_REACTOR_EVENT_USER_PRE_CREATE;
    axiam_reactor_decision_t answer = axiam_reactor_router_handler()(&event, router);
    TEST_ASSERT_EQUAL_INT(1, fell_back);
    TEST_ASSERT_EQUAL(AXIAM_REACTOR_DENY, answer.kind);

    axiam_reactor_router_free(router);
}

void test_router_a_patch_is_not_filtered_on_its_way_through(void) {
    /* Rule 6. A binder sits between the handler and the runtime and is therefore
     * the newest place to be tempted into "helpfully" pruning a forbidden key. */
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    axiam_error_t err;
    axiam_reactor_router_on(router, AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, leak_patch, NULL, &err);

    axiam_reactor_event_t event;
    memset(&event, 0, sizeof(event));
    event.event = AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE;
    axiam_reactor_decision_t answer = axiam_reactor_router_handler()(&event, router);
    TEST_ASSERT_EQUAL_size_t(2, answer.patch_count);

    axiam_reactor_router_free(router);
}

void test_router_reports_the_events_it_bound(void) {
    axiam_reactor_router_t *router = axiam_reactor_router_new();
    axiam_error_t err;
    axiam_reactor_router_on(router, AXIAM_REACTOR_EVENT_TOKEN_PRE_ISSUE, mark_token, NULL, &err);
    axiam_reactor_router_on(router, AXIAM_REACTOR_EVENT_LOGIN_POST_AUTH, mark_login, NULL, &err);

    size_t count = 0;
    const char *const *bound = axiam_reactor_router_bound_events(router, &count);
    TEST_ASSERT_EQUAL_size_t(2, count);
    /* So the author can compute §22.8's default from the code that actually
     * handles the events rather than from a restatement of the registration. */
    TEST_ASSERT_EQUAL_STRING("fail_closed", axiam_reactor_default_failure_policy(bound, count));

    axiam_reactor_router_free(router);
}

void test_router_null_arguments_are_refused(void) {
    axiam_error_t err;
    size_t count = 99;
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK, axiam_reactor_router_on(NULL, "x", mark_login, NULL, &err));
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK, axiam_reactor_router_fallback(NULL, mark_login, NULL, &err));
    TEST_ASSERT_NULL(axiam_reactor_router_bound_events(NULL, &count));
    TEST_ASSERT_EQUAL_size_t(0, count);
    axiam_reactor_router_free(NULL);

    axiam_reactor_router_t *router = axiam_reactor_router_new();
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK,
                          axiam_reactor_router_on(router, NULL, mark_login, NULL, &err));
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK, axiam_reactor_router_fallback(router, NULL, NULL, &err));
    axiam_reactor_router_free(router);
}

/* ------------------------------------------------------------------ */
/* §8b rules 1–5 — the broker URL guard                               */
/* ------------------------------------------------------------------ */

void test_amqps_guard_accepts_and_parses_an_amqps_url(void) {
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_amqps_endpoint("amqps://broker.internal:5671/prod", NULL,
                                                     NULL, NULL, &endpoint, &err));
    TEST_ASSERT_EQUAL_STRING("broker.internal", endpoint.host);
    TEST_ASSERT_EQUAL_INT(5671, endpoint.port);
    TEST_ASSERT_EQUAL_STRING("prod", endpoint.virtual_host);
    TEST_ASSERT_EQUAL_STRING("amqps://broker.internal:5671/prod", endpoint.url);
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_defaults_the_port_and_vhost(void) {
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_amqps_endpoint("amqps://broker.internal", NULL, NULL, NULL, &endpoint,
                                           &err));
    TEST_ASSERT_EQUAL_INT(5671, endpoint.port);
    TEST_ASSERT_EQUAL_STRING("/", endpoint.virtual_host);
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_refuses_plaintext_and_every_other_scheme(void) {
    /* Rule 1, and rule 5's posture: a failed amqps:// connection is an error to
     * surface, not a condition to work around — so there is no way to express a
     * plaintext fallback here at all. */
    const char *urls[] = {"amqp://broker:5672", "http://broker",   "https://broker",
                          "amqps.evil://broker", "broker:5671",   "",
                          "amqpss://broker"};
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    for (int i = 0; i < 7; i++) {
        TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                          axiam_amqps_endpoint(urls[i], NULL, NULL, NULL, &endpoint, &err));
        axiam_amqps_endpoint_dispose(&endpoint);
    }
}

void test_amqps_guard_has_no_loopback_exception(void) {
    /* §8b rule 8. §6's http://localhost dev carve-out does not extend to the
     * broker URL — they are different rules, and the server has no plaintext
     * listener for such an exception to reach. */
    const char *urls[] = {"amqp://localhost:5672", "amqp://127.0.0.1:5672", "amqp://[::1]:5672"};
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    for (int i = 0; i < 3; i++) {
        TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                          axiam_amqps_endpoint(urls[i], NULL, NULL, NULL, &endpoint, &err));
        axiam_amqps_endpoint_dispose(&endpoint);
    }
    /* And the TLS form of the same hosts is fine. */
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_amqps_endpoint("amqps://localhost:5671", NULL, NULL, NULL, &endpoint,
                                           &err));
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_is_case_insensitive_on_the_scheme(void) {
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_amqps_endpoint("AMQPS://broker.internal", NULL, NULL, NULL,
                                                     &endpoint, &err));
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_half_a_client_identity_fails_closed(void) {
    /* Rule 3. Connecting without the mutual half would present no client identity
     * at all while the caller believes one was configured. */
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH, axiam_amqps_endpoint("amqps://broker", NULL, "CERT", NULL,
                                                           &endpoint, &err));
    axiam_amqps_endpoint_dispose(&endpoint);
    TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH, axiam_amqps_endpoint("amqps://broker", NULL, NULL, "KEY",
                                                           &endpoint, &err));
    axiam_amqps_endpoint_dispose(&endpoint);
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_amqps_endpoint("amqps://broker", NULL, "CERT", "KEY",
                                                     &endpoint, &err));
    TEST_ASSERT_EQUAL_STRING("CERT", endpoint.client_cert_pem);
    TEST_ASSERT_EQUAL_STRING("KEY", endpoint.client_key_pem);
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_carries_a_custom_ca_bundle(void) {
    /* Rule 2 — the common case, and the reason nobody has a legitimate need for
     * rule 4 to be relaxed: an in-cluster broker's certificate is not issued by a
     * public CA. */
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_amqps_endpoint("amqps://broker", "CA-PEM", NULL, NULL,
                                                     &endpoint, &err));
    TEST_ASSERT_EQUAL_STRING("CA-PEM", endpoint.ca_pem);
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_strips_userinfo_from_the_host(void) {
    /* Credentials belong to the connection, not to this check — and leaving them
     * in `host` would put them wherever host is logged. */
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK,
                      axiam_amqps_endpoint("amqps://user:pass@broker.internal:5671/v", NULL, NULL,
                                           NULL, &endpoint, &err));
    TEST_ASSERT_EQUAL_STRING("broker.internal", endpoint.host);
    TEST_ASSERT_NULL(strstr(endpoint.host, "pass"));
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_keeps_an_ipv6_literal_intact(void) {
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    TEST_ASSERT_EQUAL(AXIAM_OK, axiam_amqps_endpoint("amqps://[2001:db8::1]:5671/prod", NULL,
                                                     NULL, NULL, &endpoint, &err));
    TEST_ASSERT_EQUAL_STRING("2001:db8::1", endpoint.host);
    TEST_ASSERT_EQUAL_INT(5671, endpoint.port);
    axiam_amqps_endpoint_dispose(&endpoint);
}

void test_amqps_guard_fails_closed_on_an_unusable_endpoint(void) {
    /* A URL this cannot read is not a URL it can vouch for. */
    const char *urls[] = {"amqps://", "amqps://broker:0", "amqps://broker:99999",
                          "amqps://[2001:db8::1"};
    axiam_amqps_endpoint_t endpoint;
    axiam_error_t err;
    for (int i = 0; i < 4; i++) {
        TEST_ASSERT_EQUAL(AXIAM_ERR_AUTH,
                          axiam_amqps_endpoint(urls[i], NULL, NULL, NULL, &endpoint, &err));
        axiam_amqps_endpoint_dispose(&endpoint);
    }
    TEST_ASSERT_NOT_EQUAL(AXIAM_OK,
                          axiam_amqps_endpoint(NULL, NULL, NULL, NULL, &endpoint, &err));
    axiam_amqps_endpoint_dispose(NULL);
}

int main(void) {
    FILE *f = fopen(AXIAM_REACTOR_VECTORS, "rb");
    if (!f) {
        fprintf(stderr, "cannot open the §22.13 reference vectors at %s\n",
                AXIAM_REACTOR_VECTORS);
        return 2;
    }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *text = malloc((size_t)n + 1);
    if (fread(text, 1, (size_t)n, f) != (size_t)n) {
        fclose(f);
        return 2;
    }
    text[n] = '\0';
    fclose(f);
    g_vectors = cJSON_Parse(text);
    free(text);
    if (!g_vectors) {
        fprintf(stderr, "the §22.13 reference vectors are not valid JSON\n");
        return 2;
    }

    UNITY_BEGIN();
    RUN_TEST(test_every_committed_reply_vector_reproduces_its_bytes_and_mac);
    RUN_TEST(test_require_mfa_is_omitted_when_false);
    RUN_TEST(test_reason_and_patch_are_omitted_when_absent);
    RUN_TEST(test_the_nonce_is_inside_the_signed_bytes);
    RUN_TEST(test_a_mutate_never_becomes_allow_plus_patch);
    RUN_TEST(test_a_forbidden_patch_key_is_sent_unfiltered);
    RUN_TEST(test_a_patch_is_emitted_in_byte_order);
    RUN_TEST(test_string_escaping_is_serde_jsons);
    RUN_TEST(test_require_mfa_on_any_other_event_is_refused);
    RUN_TEST(test_an_empty_mutate_is_refused);
    RUN_TEST(test_an_abstention_has_no_wire_form);
    RUN_TEST(test_the_test_signer_reproduces_the_committed_vectors);
    RUN_TEST(test_every_committed_event_vector_verifies);
    RUN_TEST(test_an_event_fails_under_any_other_key);
    RUN_TEST(test_tampering_with_any_signed_field_invalidates_the_event);
    RUN_TEST(test_key_version_below_two_is_refused_before_the_signature);
    RUN_TEST(test_freshness_is_refused_in_both_directions);
    RUN_TEST(test_a_repeated_nonce_is_refused_as_a_replay);
    RUN_TEST(test_an_event_for_another_tenant_is_refused_after_the_mac);
    RUN_TEST(test_an_unregistered_operation_is_refused_after_the_mac);
    RUN_TEST(test_an_unparseable_issued_at_is_malformed_not_stale);
    RUN_TEST(test_a_body_missing_a_signed_field_is_malformed);
    RUN_TEST(test_a_body_that_is_not_json_is_malformed);
    RUN_TEST(test_an_event_with_no_signature_at_all_is_refused);
    RUN_TEST(test_the_correlation_replay_vector_does_not_transfer);
    RUN_TEST(test_token_pre_issue_admits_the_ext_namespace_and_nothing_else);
    RUN_TEST(test_user_pre_create_admits_its_fields_and_its_namespace);
    RUN_TEST(test_the_veto_only_events_accept_no_patch_field);
    RUN_TEST(test_the_hot_path_operations_are_absent_from_every_exposed_constant);
    RUN_TEST(test_the_strictest_default_wins_in_either_order);
    RUN_TEST(test_the_topology_names_match_the_vectors);
    RUN_TEST(test_the_runtime_verifies_dispatches_and_publishes);
    RUN_TEST(test_an_unverifiable_delivery_produces_no_reply);
    RUN_TEST(test_an_abstaining_handler_produces_no_reply);
    RUN_TEST(test_a_reply_the_builder_refuses_produces_no_reply);
    RUN_TEST(test_the_runtime_keeps_one_nonce_set_for_its_whole_lifetime);
    RUN_TEST(test_two_deliveries_with_different_nonces_both_dispatch);
    RUN_TEST(test_the_reply_never_carries_the_signing_key);
    RUN_TEST(test_serve_refuses_a_missing_handler_config_or_tenant);
    RUN_TEST(test_router_two_events_reach_their_own_handlers);
    RUN_TEST(test_router_a_name_outside_the_registry_is_refused_at_bind_time);
    RUN_TEST(test_router_a_hot_path_operation_is_refused_like_any_unknown_name);
    RUN_TEST(test_router_a_second_binding_is_an_error_not_an_overwrite);
    RUN_TEST(test_router_an_unbound_event_abstains);
    RUN_TEST(test_router_an_explicit_fallback_is_honoured_and_has_no_default);
    RUN_TEST(test_router_a_patch_is_not_filtered_on_its_way_through);
    RUN_TEST(test_router_reports_the_events_it_bound);
    RUN_TEST(test_router_null_arguments_are_refused);
    RUN_TEST(test_amqps_guard_accepts_and_parses_an_amqps_url);
    RUN_TEST(test_amqps_guard_defaults_the_port_and_vhost);
    RUN_TEST(test_amqps_guard_refuses_plaintext_and_every_other_scheme);
    RUN_TEST(test_amqps_guard_has_no_loopback_exception);
    RUN_TEST(test_amqps_guard_is_case_insensitive_on_the_scheme);
    RUN_TEST(test_amqps_guard_half_a_client_identity_fails_closed);
    RUN_TEST(test_amqps_guard_carries_a_custom_ca_bundle);
    RUN_TEST(test_amqps_guard_strips_userinfo_from_the_host);
    RUN_TEST(test_amqps_guard_keeps_an_ipv6_literal_intact);
    RUN_TEST(test_amqps_guard_fails_closed_on_an_unusable_endpoint);
    int rc = UNITY_END();
    cJSON_Delete(g_vectors);
    return rc;
}
