#!/usr/bin/env python3
"""Generate the CONTRACT §27 management surface for the C SDK.

Reads ``management-registry.json`` (the 146 operations across 24 namespaces,
maintained in ``ilpanich/axiam`` and vendored here) plus ``openapi.json``, and writes:

- ``include/axiam/management_models.h`` — one struct or enum per request and response
  type, plus a ``_free`` for every owning struct;
- ``include/axiam/management_ops.h`` — the 146 flat operation declarations (§27.3);
- ``src/management_models.c`` — parse and free for every model;
- ``src/management_ops.c`` — the 146 operation bodies;
- ``tests/test_management_generated.c`` — one conformance case per operation.

Run with ``--check`` to verify the committed output is current; that is what CI runs.

C makes two demands the other ports do not. **Every allocation needs a matching free**,
so a model is not just a struct but a struct plus a ``_free`` that walks it, and a parse
that fails halfway must not leak what it already built. And **there is no subtyping**, so
§27.4 rule 7 becomes a classification function beside the error rather than a hierarchy
inside it (see ``include/axiam/management.h``).
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY: dict[str, Any] = json.loads((ROOT / "management-registry.json").read_text())
SPEC: dict[str, Any] = json.loads((ROOT / "openapi.json").read_text())
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]

BANNER = """<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
"""

# §27.4 rule 3: `{org_id}` always defaults from the client. `{tenant_id}`
# defaults from the client only where it names the *context*; in `tenants` and
# the signing-CA routes it names the object being acted on.
IMPLICIT_TENANT_NAMESPACES = {"email_config", "settings", "webauthn_policy"}

# Schema names that would collide with a type this SDK already exports. The models
# live in their own PHP namespace (Axiam\Sdk\Management\Models), so a collision can
# only happen against another MODEL -- which the spec itself prevents.
RENAMED_SCHEMAS: dict[str, str] = {}

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def pascal(text: str) -> str:
    """``service_accounts`` -> ``ServiceAccounts``; already-Pascal input is kept.

    Deliberately does NOT normalise initialisms, so every generated type name can be
    grepped straight out of ``openapi.json``.
    """
    if "_" not in text and "-" not in text and text[:1].isupper():
        return RENAMED_SCHEMAS.get(text, text)
    parts = [p for p in text.replace("-", "_").replace(" ", "_").split("_") if p]
    joined = "".join(p[0].upper() + p[1:] for p in parts)
    return RENAMED_SCHEMAS.get(joined, joined)


def camel(text: str) -> str:
    """``service_accounts`` -> ``serviceAccounts``; the PHP property spelling."""
    out = pascal(text)
    return out[0].lower() + out[1:] if out else out


# PHP reserved words that cannot be used bare as a method name on a class.
# (Property names are far less restricted, but methods share the keyword space.)
PHP_KEYWORDS = {
    "abstract", "and", "array", "as", "break", "callable", "case", "catch",
    "class", "clone", "const", "continue", "declare", "default", "do", "echo",
    "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif",
    "endswitch", "endwhile", "enum", "eval", "exit", "extends", "final",
    "finally", "fn", "for", "foreach", "function", "global", "goto", "if",
    "implements", "include", "instanceof", "insteadof", "interface", "isset",
    "list", "match", "namespace", "new", "or", "print", "private", "protected",
    "public", "readonly", "require", "return", "static", "switch", "throw",
    "trait", "try", "unset", "use", "var", "while", "xor", "yield",
}


def prop(name: str) -> str:
    """A PHP property name for a wire field. Properties may be keywords; methods may not."""
    return camel(name)


def method(name: str) -> str:
    """A PHP-legal method name for ``name``.

    ``list`` is a language construct and cannot be a bare method name in the PHP
    versions this SDK supports, and it is also the single most common §27 operation
    name -- so the suffix rule earns its keep on the very first namespace.
    """
    ident = camel(name)
    return f"{ident}Items" if ident.lower() in PHP_KEYWORDS else ident


def snake(text: str) -> str:
    """``ServiceAccounts`` -> ``service_accounts``; already-snake input is kept."""
    out: list[str] = []
    for i, ch in enumerate(text):
        boundary = not text[i - 1].isupper() or (i + 1 < len(text) and text[i + 1].islower())
        if ch.isupper() and i and boundary:
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_").replace("__", "_")


def wrap(text: str, width: int = 76) -> list[str]:
    """Reflow ``text`` into paragraph-preserving lines."""
    out: list[str] = []
    for para in str(text).strip().split("\n\n"):
        words = para.split()
        if not words:
            continue
        line = ""
        for word in words:
            if line and len(line) + 1 + len(word) > width:
                out.append(line)
                line = word
            else:
                line = f"{line} {word}" if line else word
        if line:
            out.append(line)
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return out


def escape(text: str) -> str:
    """Make an ``openapi.json`` description safe to paste into a PHP docblock.

    A docblock is delimited by ``*/``, so a description containing one would close the
    comment early and spill the rest into code -- the PHP analogue of the nested-KDoc
    bug the Kotlin port hit. Both ``*/`` and ``/*`` are neutralised.
    """
    out = " ".join(str(text).split())
    return out.replace("*/", "* /").replace("/*", "/ *")


def docblock(text: str, indent: str = "", tags: list[str] | None = None) -> list[str]:
    """A wrapped docblock at ``indent``, with optional trailing ``@``-tag lines."""
    paragraphs = [p for p in str(text).split("\n\n") if p.strip()]
    width = 92 - len(indent)
    out = [f"{indent}/**"]
    first = True
    for para in paragraphs or [""]:
        if not first:
            out.append(f"{indent} *")
        for line in wrap(para, width):
            out.append(f"{indent} * {line}".rstrip())
        first = False
    for tag in tags or []:
        lines = wrap(tag, width)
        out.append(f"{indent} * {lines[0]}")
        out.extend(f"{indent} *     {more}" for more in lines[1:])
    out.append(f"{indent} */")
    return out


def inline_doc(text: str, indent: str = "") -> list[str]:
    """A one-line docblock, or a wrapped block when it will not fit."""
    single = f"{indent}/** {text} */"
    if len(single) <= 100 and "\n" not in text:
        return [single]
    return docblock(text, indent)


def resolve_ref(schema: Any) -> Any:
    """Follow ``$ref`` chains to the schema they name."""
    node = schema
    while isinstance(node, dict) and "$ref" in node:
        node = SCHEMAS.get(node["$ref"].split("/")[-1], {})
    return node


def nullable_ref(schema: Any) -> str | None:
    """``{oneOf: [{type: null}, {$ref: X}]}`` -- utoipa's optional-enum shape."""
    variants = schema.get("oneOf") if isinstance(schema, dict) else None
    if not isinstance(variants, list) or len(variants) != 2:
        return None
    nulls = [v for v in variants if v.get("type") == "null"]
    refs = [v for v in variants if "$ref" in v]
    return refs[0]["$ref"].split("/")[-1] if len(nulls) == 1 and len(refs) == 1 else None


def flatten(name: str) -> tuple[dict[str, Any], set[str], str | None]:
    """Properties, required set and description of ``name``, ``allOf`` resolved."""
    props: dict[str, Any] = {}
    required: set[str] = set()

    def absorb(node: Any) -> None:
        """Merge one ``allOf`` member's properties into the accumulator."""
        resolved = resolve_ref(node) if "$ref" in node else node
        props.update(resolved.get("properties") or {})
        required.update(resolved.get("required") or [])
        for sub in resolved.get("allOf") or []:
            absorb(sub)

    schema = SCHEMAS.get(name, {})
    absorb(schema)
    return props, required, schema.get("description")


def discriminated(schema: Any) -> tuple[str, list[tuple[str, Any]]] | None:
    """Detect an internally-tagged union and return ``(tag, [(value, payload)])``."""
    variants = schema.get("oneOf")
    if not isinstance(variants, list) or len(variants) < 2:
        return None
    tag: str | None = None
    arms: list[tuple[str, Any]] = []
    for variant in variants:
        parts = variant.get("allOf") or [variant]
        value: str | None = None
        payload: Any = None
        leftovers: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in parts:
            if "$ref" in part:
                payload = part
                continue
            for pname, pschema in (part.get("properties") or {}).items():
                enum = pschema.get("enum")
                if pschema.get("type") == "string" and isinstance(enum, list) and len(enum) == 1:
                    if tag and tag != pname:
                        return None
                    tag = pname
                    value = enum[0]
                else:
                    leftovers["properties"][pname] = pschema
                    if pname in (part.get("required") or []):
                        leftovers["required"].append(pname)
        if value is None:
            return None
        arms.append((value, payload if payload is not None else leftovers))
    return (tag or "", arms)


def sensitive_map() -> dict[str, set[str]]:
    """Which fields of which schemas carry a secret, per the registry."""
    out: dict[str, set[str]] = {}
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                key = op["request_schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_request_fields"])
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                key = op["response"]["schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_response_fields"])
    return out


def schema_closure() -> list[str]:
    """Every schema reachable from an operation, transitively, sorted."""
    seeds: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"]:
                seeds.add(op["request_schema"].lstrip("[]"))
            if op["response"]["schema"]:
                seeds.add(op["response"]["schema"].lstrip("[]"))

    def refs_in(node: Any, found: set[str]) -> None:
        """Collect every ``$ref`` target name appearing anywhere under ``node``."""
        if isinstance(node, list):
            for item in node:
                refs_in(item, found)
        elif isinstance(node, dict):
            if "$ref" in node:
                found.add(node["$ref"].split("/")[-1])
            for value in node.values():
                refs_in(value, found)

    seen: set[str] = set()
    frontier = list(seeds)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in SCHEMAS:
            continue
        seen.add(name)
        found: set[str] = set()
        refs_in(SCHEMAS[name], found)
        frontier.extend(f for f in found if f not in seen)
    return sorted(seen)



def _classify() -> tuple[set[str], set[str]]:
    """Split the spec's schemas into (enums, discriminated unions), by RENDERED name.

    Computed once, up front. A type's NAME never tells you its KIND, and an emitter that
    re-guesses from a name is how a sibling port shipped `Enum::fromArray()` on a backed
    enum.
    """
    enums: set[str] = set()
    unions: set[str] = set()
    for name, schema in SCHEMAS.items():
        if not isinstance(schema, dict):
            continue
        if isinstance(schema.get("enum"), list):
            enums.add(pascal(name))
        elif discriminated(schema):
            unions.add(pascal(name))
    return enums, unions


ENUMS, UNIONS = _classify()


# ---------------------------------------------------------------------------
# C naming and types
# ---------------------------------------------------------------------------

MODELS_H = "include/axiam/management_models.h"
OPS_H = "include/axiam/management_ops.h"
MODELS_C = "src/management_models.c"
OPS_C = "src/management_ops.c"
TEST_C = "tests/test_management_generated.c"
MODEL_TEST_C = "tests/test_management_models_generated.c"
ALLOC_TEST_C = "tests/test_management_alloc_generated.c"

BANNER_C = """/*
 * Generated by scripts/gen_management.py from management-registry.json and openapi.json.
 * DO NOT EDIT -- your changes will be overwritten. Regenerate with
 * `python3 scripts/gen_management.py`; CI verifies the committed output is current.
 */
"""

C_KEYWORDS = {
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double",
    "else", "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long",
    "register", "restrict", "return", "short", "signed", "sizeof", "static", "struct",
    "switch", "typedef", "union", "unsigned", "void", "volatile", "while", "bool",
    "complex", "imaginary",
}


def cname(text: str) -> str:
    """A C identifier fragment: lower snake_case, keywords suffixed."""
    ident = snake(pascal(text))
    return f"{ident}_" if ident in C_KEYWORDS else ident


# Type names the HAND-WRITTEN core already owns in the axiam_mgmt_ namespace. A model
# that rendered to one of these would silently redefine it -- which is exactly what
# `Scope` did on the first run, since the spec has a schema by that name and
# management.h had a struct by that name. The generated model keeps the spec's name
# (renaming it would make C the one SDK whose type does not match the contract) and the
# hand-written one carries a qualifier; this list is what makes the NEXT such collision
# a build failure here rather than a confusing redefinition error 4000 lines into a
# generated header.
RESERVED_TYPES = {
    "axiam_mgmt_call_scope_t",
    "axiam_mgmt_page_req_t",
    "axiam_mgmt_error_class_t",
}


def model_type(name: str) -> str:
    """The C typedef name for a model (``Role`` -> ``axiam_mgmt_role_t``)."""
    rendered = f"axiam_mgmt_{snake(pascal(name))}_t"
    if rendered in RESERVED_TYPES:
        raise SystemExit(
            f"schema {name!r} renders to {rendered!r}, which the hand-written core in "
            "include/axiam/management.h already defines. Rename the hand-written type "
            "and add the new name to RESERVED_TYPES -- do NOT rename the model, or C "
            "becomes the one SDK whose type does not match the contract."
        )
    return rendered


def model_prefix(name: str) -> str:
    """The C function prefix for a model (``Role`` -> ``axiam_mgmt_role``)."""
    return f"axiam_mgmt_{snake(pascal(name))}"


def enum_const(model: str, value: str) -> str:
    """A C enum constant (``UserStatus``/``Active`` -> ``AXIAM_MGMT_USER_STATUS_ACTIVE``)."""
    tail = snake(pascal(value)).upper()
    if not tail or not tail[0].isalpha():
        tail = f"V{tail}"
    return f"AXIAM_MGMT_{snake(pascal(model)).upper()}_{tail}"


def comment(text: str, indent: str = "", width: int = 92) -> list[str]:
    """A block comment at ``indent``. C89-style, since this compiles at -std=c11 and below."""
    lines = wrap(escape(text), width - len(indent) - 3)
    if len(lines) == 1:
        return [f"{indent}/* {lines[0]} */"]
    out = [f"{indent}/*"]
    out.extend(f"{indent} * {line}".rstrip() for line in lines)
    out.append(f"{indent} */")
    return out


def doc(text: str, indent: str = "", width: int = 92) -> list[str]:
    """A Doxygen block at ``indent`` -- this repo publishes an API reference from them."""
    paragraphs = [p for p in str(text).split("\n\n") if p.strip()]
    out = [f"{indent}/**"]
    first = True
    for para in paragraphs or [""]:
        if not first:
            out.append(f"{indent} *")
        for line in wrap(escape(para), width - len(indent) - 3):
            out.append(f"{indent} * {line}".rstrip())
        first = False
    out.append(f"{indent} */")
    return out


def c_field(schema: Any, secret: bool = False) -> dict[str, str]:
    """Map a schema to how one struct member is declared, parsed and freed.

    Returns a dict with ``decl`` (the C type), ``kind`` (a tag the emitters switch on)
    and, for references, ``ref`` (the schema name).
    """
    if secret:
        return {"decl": "axiam_sensitive_t *", "kind": "sensitive", "ref": ""}
    if not isinstance(schema, dict):
        return {"decl": "char *", "kind": "json_text", "ref": ""}

    if "$ref" in schema:
        name = pascal(schema["$ref"].split("/")[-1])
        if name in ENUMS:
            return {"decl": f"axiam_mgmt_{snake(name)}_t ", "kind": "enum", "ref": name}
        return {"decl": f"{model_type(name)} *", "kind": "model", "ref": name}

    inner = nullable_ref(schema)
    if inner:
        name = pascal(inner)
        if name in ENUMS:
            return {"decl": f"axiam_mgmt_{snake(name)}_t ", "kind": "enum", "ref": name}
        return {"decl": f"{model_type(name)} *", "kind": "model", "ref": name}

    if isinstance(schema.get("allOf"), list) and len(schema["allOf"]) == 1:
        return c_field(schema["allOf"][0])

    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)

    if kind == "array":
        item = c_field(schema.get("items") or {})
        if item["kind"] == "string":
            return {"decl": "char **", "kind": "string_array", "ref": ""}
        if item["kind"] == "model":
            return {"decl": f"{model_type(item['ref'])} **", "kind": "model_array",
                    "ref": item["ref"]}
        # Anything else (numbers, nested arrays, free-form objects) is kept as raw JSON
        # rather than given a bespoke C representation nobody would enjoy freeing.
        return {"decl": "char *", "kind": "json_text", "ref": ""}
    if kind == "integer":
        return {"decl": "long ", "kind": "long", "ref": ""}
    if kind == "number":
        return {"decl": "double ", "kind": "double", "ref": ""}
    if kind == "boolean":
        return {"decl": "int ", "kind": "bool", "ref": ""}
    if kind == "string":
        return {"decl": "char *", "kind": "string", "ref": ""}

    return {"decl": "char *", "kind": "json_text", "ref": ""}


def scalar(kind: str) -> bool:
    """True for a member that needs a companion ``has_`` flag when optional.

    A pointer member says "absent" by being NULL. A `long`, `double` or `int` cannot,
    and picking a sentinel (0? -1?) would collide with a value the server can legitimately
    send -- so optional scalars carry an explicit presence flag instead.
    """
    return kind in {"long", "double", "bool", "enum"}


PROJECTION_DOC = (
    "Resolved by the list projection only.\n\n"
    "The server resolves this for a whole page in one query, so it is populated by "
    "`list` and is NULL on `get` (CONTRACT.md \u00a727.11 rule 4). NULL there means \"this "
    "read does not carry it\", not \"there is nothing bound\" -- this SDK does not issue a "
    "second request to fill it in."
)


def projection_map() -> dict[str, list[dict[str, Any]]]:
    """Members a list projection ADDS to its base schema, keyed by the base's name.

    \u00a727.11 rule 4: the server expresses a projection as an ``allOf`` of the named base
    and an anonymous object, so the added property belongs to no schema in
    ``components``. The registry records it as ``response.projected_fields``; this folds
    it back onto the base struct as an OPTIONAL member, which is what makes it NULL on
    the ``get`` that does not project it rather than absent from the type.
    """
    added: dict[str, list[dict[str, Any]]] = {}
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            response = op.get("response") or {}
            extras = response.get("projected_fields") or []
            base = (response.get("schema") or "").lstrip("[]")
            if not extras or not base:
                continue
            known = {f["name"] for f in added.setdefault(base, [])}
            for extra in extras:
                if extra["name"] not in known:
                    added[base].append(extra)
    return added


PROJECTED: dict[str, list[dict[str, Any]]] = projection_map()


def fields_of(schema_name: str, secrets: set[str]) -> tuple[list[dict[str, Any]], str | None]:
    """Every member of ``schema_name``, in the spec's own order.

    A discriminated union gets two synthetic members instead: the discriminator as a
    string, and the whole object as raw JSON. C has no sum type, and a hand-rolled tagged
    union of five arms would hand the caller a `free()` maze for a shape this SDK only
    ever forwards -- so the tag is what you branch on and the payload stays inspectable.
    """
    schema = SCHEMAS.get(schema_name) or {}
    union = discriminated(schema)
    if union:
        tag, _arms = union
        return ([
            {
                "wire": tag, "name": cname(tag), "decl": "char *", "kind": "string",
                "ref": "", "required": True, "schema": {"type": "string"}, "secret": False,
                "description": f"The `{tag}` discriminator naming which variant this is.",
            },
            {
                "wire": "", "name": "raw", "decl": "char *", "kind": "union_raw",
                "ref": "", "required": False, "schema": {}, "secret": False,
                "description": "The whole object as the server sent it, to read the "
                               "variant's own fields from once `"
                               + tag + "` says which variant it is.",
            },
        ], schema.get("description"))

    props, required, description = flatten(schema_name)
    props = dict(props)
    for extra in PROJECTED.get(schema_name, []):
        if extra["name"] in props:
            continue
        # Never added to `required`: the whole point is that the operation which does NOT
        # project it still parses, with the member NULL (\u00a727.11 rule 4).
        props[extra["name"]] = {
            "type": extra["type"],
            "format": extra.get("format"),
            "description": extra.get("description") or PROJECTION_DOC,
        }
    out: list[dict[str, Any]] = []
    for wire, schema in props.items():
        info = c_field(schema, secret=wire in secrets)
        out.append({
            "wire": wire,
            "name": cname(wire),
            "decl": info["decl"],
            "kind": info["kind"],
            "ref": info["ref"],
            "required": wire in required,
            "schema": schema,
            "secret": wire in secrets,
            "description": schema.get("description") if isinstance(schema, dict) else None,
        })
    return out, description


def field_doc(f: dict[str, Any]) -> str:
    """The one-line description for a member."""
    if f["description"]:
        return escape(f["description"])
    if f["secret"]:
        return f"The server's `{f['wire']}` field -- a ONE-TIME secret (27.5)."
    return f"The server's `{f['wire']}` field."


# ---------------------------------------------------------------------------
# Models: header
# ---------------------------------------------------------------------------


def paginated_models() -> list[str]:
    """Response schemas returned as a page -- each gets a typed page struct."""
    out: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["response"]["kind"] == "page" and op["response"]["schema"]:
                out.add(pascal(op["response"]["schema"].lstrip("[]")))
    return sorted(out)


def array_models() -> list[str]:
    """Response schemas returned as a BARE ARRAY (27.4 rule 4: never a page)."""
    out: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["response"]["kind"] == "array" and op["response"]["schema"]:
                out.add(pascal(op["response"]["schema"].lstrip("[]")))
    return sorted(out)


def emit_models_header() -> str:
    """The generated model structs, enums, page/list wrappers and free declarations."""
    secrets = sensitive_map()
    out = [BANNER_C]
    out.append("")
    out.append("#ifndef AXIAM_MANAGEMENT_MODELS_H")
    out.append("#define AXIAM_MANAGEMENT_MODELS_H")
    out.append("")
    out.append("#include <stddef.h>")
    out.append("")
    out.append('#include "axiam/management.h"')
    out.append('#include "axiam/sensitive.h"')
    out.append("")
    out.extend(comment(
        "A free-form JSON member (`metadata`, `attribute_map`) is raw JSON TEXT, not a "
        "parsed tree. Every other public header in this SDK keeps the bundled cJSON "
        "internal, and exposing it here would put a third-party type in the installed "
        "ABI -- forcing cJSON onto every consumer's include path to name a field they "
        "will hand to their own parser anyway."))
    out.append("")
    out.append("#ifdef __cplusplus")
    out.append('extern "C" {')
    out.append("#endif")
    out.append("")

    # ---- enums ----
    for name in schema_closure():
        rendered = pascal(name)
        if rendered not in ENUMS:
            continue
        schema = SCHEMAS.get(name) or {}
        values = [str(v) for v in (schema.get("enum") or [])]
        if not values:
            continue
        out.extend(doc(schema.get("description")
                       or f"The `{rendered}` enumeration from the server's OpenAPI document."))
        if any(enum_const(rendered, v) == enum_const(rendered, "unknown") for v in values):
            raise SystemExit(
                f"enum {rendered}: the spec declares a value whose constant collides with "
                "the open-enum carrier this generator appends."
            )
        out.append(f"typedef enum axiam_mgmt_{snake(rendered)} {{")
        out.append(f"    {enum_const(rendered, values[0])} = 0, /**< Wire value `{values[0]}`. */")
        for value in values[1:]:
            out.append(f"    {enum_const(rendered, value)}, /**< Wire value `{value}`. */")
        out.append(f"    {enum_const(rendered, 'unknown')}, "
                   "/**< A value this SDK's copy of the spec does not list. */")
        out.append(f"}} axiam_mgmt_{snake(rendered)}_t;")
        out.append("")
        out.extend(doc(
            f"Parse a wire value into an {rendered}.\n\n"
            f"Returns 0 and yields `{enum_const(rendered, 'unknown')}` for a value this "
            "SDK's copy of the spec does not list, rather than reporting a failure the "
            "caller would have to fail the whole record over (CONTRACT.md \u00a727.11 rule 1). "
            "Returns -1 only for a NULL argument.\n\n"
            "It is never mapped to one of the KNOWN constants, which is the trap this used "
            "to avoid by failing: reading a new state as whichever constant happens to be "
            "first turns a new server state into a wrong one, and on this surface these "
            "values gate access. The unknown constant is appended LAST, so it is never the "
            "zero value a calloc'd struct starts at either."))
        out.append(f"int axiam_mgmt_{snake(rendered)}_from_wire(const char *value, "
                   f"axiam_mgmt_{snake(rendered)}_t *out);")
        out.append("")
        out.extend(doc(
            f"The wire spelling of an {rendered}. Never NULL.\n\n"
            f"`{enum_const(rendered, 'unknown')}` spells as the empty string, which no "
            "server value is: carrying an unrecognised value back into an update is refused "
            "by the server rather than written as a spelling it never used."))
        out.append(f"const char *axiam_mgmt_{snake(rendered)}_to_wire("
                   f"axiam_mgmt_{snake(rendered)}_t value);")
        out.append("")

    # ---- forward declarations, so models may reference each other in any order ----
    structs = [pascal(n) for n in schema_closure()
               if pascal(n) not in ENUMS and (flatten(n)[0] or discriminated(SCHEMAS.get(n) or {}))]
    out.extend(comment(
        "Forward declarations. The spec's types reference each other freely and in both "
        "directions, so every struct is named before any is defined."))
    for name in structs:
        out.append(f"typedef struct axiam_mgmt_{snake(name)} {model_type(name)};")
    out.append("")

    # ---- structs ----
    for name in schema_closure():
        rendered = pascal(name)
        if rendered in ENUMS:
            continue
        fields, description = fields_of(name, secrets.get(name, set()))
        if not fields:
            continue

        summary = escape(description) if description else \
            f"The `{rendered}` schema from the server's OpenAPI document."
        sparse = all(not f["required"] for f in fields)
        if sparse:
            summary += (
                "\n\nEvery member is optional, so this is a SPARSE body (27.4 rule 5): a "
                "NULL pointer -- or a `has_` flag left 0 -- means the field is OMITTED "
                "from the request entirely, not sent as null. On a sparse update those "
                "say opposite things, and only omission means \"leave it alone\".")
        out.extend(doc(summary))
        out.append(f"struct axiam_mgmt_{snake(rendered)} {{")
        for f in fields:
            out.extend(doc(field_doc(f) + ("" if f["required"] else " Optional."), "    "))
            if f["kind"] in {"string_array", "model_array"}:
                out.append(f"    {f['decl']}{f['name']};")
                out.append(f"    size_t {f['name']}_count; /**< Entries in `{f['name']}`. */")
            else:
                out.append(f"    {f['decl']}{f['name']};")
            if scalar(f["kind"]) and not f["required"]:
                out.append(f"    int has_{f['name']}; /**< 1 when `{f['name']}` is set. */")
        out.append("};")
        out.append("")
        out.extend(doc(
            f"Free a {rendered} and everything it owns. Safe to pass NULL.\n\n"
            "Frees the struct itself as well as its members, so it pairs with whatever "
            "allocated it and there is never a question of which half you own."))
        out.append(f"void {model_prefix(rendered)}_free({model_type(rendered)} *value);")
        out.append("")

    # ---- page and list wrappers ----
    for name in paginated_models():
        out.extend(doc(
            f"One page of {name} objects (27.4 rule 4).\n\n"
            "`total` is the SERVER's count across every page. It is NOT `count`, and "
            "deriving one from the other is how a management tool silently processes the "
            "first fifty of four hundred rows -- so they are separate members and neither "
            "is computed from the other."))
        out.append(f"typedef struct axiam_mgmt_{snake(name)}_page {{")
        out.append(f"    {model_type(name)} **items; /**< The items on THIS page. */")
        out.append("    size_t count;              /**< How many items are on this page. */")
        out.append("    long total;                /**< The server's total across all pages. */")
        out.append("    axiam_mgmt_page_req_t request; /**< The request that produced this page. */")
        out.append(f"}} axiam_mgmt_{snake(name)}_page_t;")
        out.append("")
        out.extend(doc(f"Free a page of {name} objects and every item in it. Safe to pass NULL."))
        out.append(f"void axiam_mgmt_{snake(name)}_page_free(axiam_mgmt_{snake(name)}_page_t *page);")
        out.append("")

    for name in array_models():
        out.extend(doc(
            f"A plain list of {name} objects.\n\n"
            "This is what a BARE-ARRAY endpoint returns. 27.4 rule 4 is explicit that "
            "such a response MUST NOT be modelled as a page: there is no `total`, no "
            "offset and no next page, and dressing it as one would invite a caller to "
            "walk something that has already ended."))
        out.append(f"typedef struct axiam_mgmt_{snake(name)}_list {{")
        out.append(f"    {model_type(name)} **items; /**< Every item the server returned. */")
        out.append("    size_t count;              /**< How many. */")
        out.append(f"}} axiam_mgmt_{snake(name)}_list_t;")
        out.append("")
        out.extend(doc(f"Free a list of {name} objects and every item in it. Safe to pass NULL."))
        out.append(f"void axiam_mgmt_{snake(name)}_list_free(axiam_mgmt_{snake(name)}_list_t *list);")
        out.append("")

    out.append("#ifdef __cplusplus")
    out.append("}")
    out.append("#endif")
    out.append("")
    out.append("#endif /* AXIAM_MANAGEMENT_MODELS_H */")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Models: implementation
# ---------------------------------------------------------------------------


def emit_parse_field(f: dict[str, Any], indent: str = "    ") -> list[str]:
    """Parse one member out of `src` into `out->name`."""
    w, n, kind = f["wire"], f["name"], f["kind"]
    o = []
    if kind == "union_raw":
        o.append(f"{indent}out->{n} = cJSON_PrintUnformatted(src);")
        return o

    o.append(f'{indent}item = cJSON_GetObjectItemCaseSensitive(src, "{w}");')

    if kind == "string":
        o.append(f"{indent}if (cJSON_IsString(item)) out->{n} = axiam_strdup0(item->valuestring);")
    elif kind == "sensitive":
        # 27.5: a one-time secret goes behind Sensitive the moment it is parsed, so it
        # cannot reach a log line by way of an ordinary struct member.
        o.append(f"{indent}if (cJSON_IsString(item)) out->{n} = axiam_sensitive_new(item->valuestring);")
    elif kind in {"long", "double"}:
        cast = "(long)" if kind == "long" else "(double)"
        o.append(f"{indent}if (cJSON_IsNumber(item)) {{ out->{n} = {cast} item->valuedouble;")
        if not f["required"]:
            o.append(f"{indent}    out->has_{n} = 1; }}")
        else:
            o.append(f"{indent}}}")
    elif kind == "bool":
        o.append(f"{indent}if (cJSON_IsBool(item)) {{ out->{n} = cJSON_IsTrue(item) ? 1 : 0;")
        if not f["required"]:
            o.append(f"{indent}    out->has_{n} = 1; }}")
        else:
            o.append(f"{indent}}}")
    elif kind == "enum":
        fn = f"axiam_mgmt_{snake(f['ref'])}_from_wire"
        o.append(f"{indent}if (cJSON_IsString(item) && {fn}(item->valuestring, &out->{n}) == 0) {{")
        if not f["required"]:
            o.append(f"{indent}    out->has_{n} = 1;")
        else:
            o.append(f"{indent}    (void) 0;")
        o.append(f"{indent}}}")
    elif kind == "model":
        o.append(f"{indent}if (cJSON_IsObject(item)) out->{n} = {model_prefix(f['ref'])}_parse(item);")
    elif kind == "json_text":
        o.append(f"{indent}if (item) out->{n} = cJSON_PrintUnformatted(item);")
    elif kind == "string_array":
        o.append(f"{indent}if (cJSON_IsArray(item)) {{")
        o.append(f"{indent}    size_t n = (size_t) cJSON_GetArraySize(item);")
        o.append(f"{indent}    if (n > 0) {{")
        o.append(f"{indent}        out->{n} = (char **) calloc(n, sizeof(char *));")
        o.append(f"{indent}        if (!out->{n}) {{ {model_prefix(f['owner'])}_free(out); return NULL; }}")
        o.append(f"{indent}        for (size_t i = 0; i < n; i++) {{")
        o.append(f"{indent}            const cJSON *e = cJSON_GetArrayItem(item, (int) i);")
        o.append(f"{indent}            if (cJSON_IsString(e)) out->{n}[i] = axiam_strdup0(e->valuestring);")
        o.append(f"{indent}        }}")
        o.append(f"{indent}        out->{n}_count = n;")
        o.append(f"{indent}    }}")
        o.append(f"{indent}}}")
    elif kind == "model_array":
        t = model_type(f["ref"])
        o.append(f"{indent}if (cJSON_IsArray(item)) {{")
        o.append(f"{indent}    size_t n = (size_t) cJSON_GetArraySize(item);")
        o.append(f"{indent}    if (n > 0) {{")
        o.append(f"{indent}        out->{n} = ({t} **) calloc(n, sizeof({t} *));")
        o.append(f"{indent}        if (!out->{n}) {{ {model_prefix(f['owner'])}_free(out); return NULL; }}")
        o.append(f"{indent}        for (size_t i = 0; i < n; i++) {{")
        o.append(f"{indent}            const cJSON *e = cJSON_GetArrayItem(item, (int) i);")
        o.append(f"{indent}            if (cJSON_IsObject(e)) out->{n}[i] = {model_prefix(f['ref'])}_parse(e);")
        o.append(f"{indent}        }}")
        o.append(f"{indent}        out->{n}_count = n;")
        o.append(f"{indent}    }}")
        o.append(f"{indent}}}")
    return o


def emit_free_field(f: dict[str, Any], indent: str = "    ") -> list[str]:
    """Release one member."""
    n, kind = f["name"], f["kind"]
    if kind == "string":
        return [f"{indent}free(value->{n});"]
    if kind == "sensitive":
        return [f"{indent}axiam_sensitive_free(value->{n});"]
    if kind == "model":
        return [f"{indent}{model_prefix(f['ref'])}_free(value->{n});"]
    if kind in {"json_text", "union_raw"}:
        return [f"{indent}free(value->{n});"]
    if kind == "string_array":
        return [
            f"{indent}if (value->{n}) {{",
            f"{indent}    for (size_t i = 0; i < value->{n}_count; i++) free(value->{n}[i]);",
            f"{indent}    free(value->{n});",
            f"{indent}}}",
        ]
    if kind == "model_array":
        return [
            f"{indent}if (value->{n}) {{",
            f"{indent}    for (size_t i = 0; i < value->{n}_count; i++) "
            f"{model_prefix(f['ref'])}_free(value->{n}[i]);",
            f"{indent}    free(value->{n});",
            f"{indent}}}",
        ]
    return []


def emit_build_field(f: dict[str, Any], indent: str = "    ") -> list[str]:
    """Serialize one member into the request body, honouring 27.4 rule 5."""
    w, n, kind = f["wire"], f["name"], f["kind"]
    o = []
    if kind in {"string", "model", "json_text", "string_array", "model_array"}:
        guard = f"if (value->{n})"
    elif kind == "sensitive":
        guard = f"if (value->{n})"
    elif f["required"]:
        guard = "if (1)"
    else:
        guard = f"if (value->has_{n})"

    if kind == "union_raw":
        return []

    o.append(f"{indent}{guard} {{")
    body = indent + "    "
    if kind == "string":
        o.append(f'{body}cJSON_AddStringToObject(obj, "{w}", value->{n});')
    elif kind == "sensitive":
        # 27.5: this is the one place a secret is revealed, on the way to the wire.
        o.append(f'{body}cJSON_AddStringToObject(obj, "{w}", axiam_sensitive_reveal(value->{n}));')
    elif kind == "long":
        o.append(f'{body}cJSON_AddNumberToObject(obj, "{w}", (double) value->{n});')
    elif kind == "double":
        o.append(f'{body}cJSON_AddNumberToObject(obj, "{w}", value->{n});')
    elif kind == "bool":
        o.append(f'{body}cJSON_AddBoolToObject(obj, "{w}", value->{n});')
    elif kind == "enum":
        fn = f"axiam_mgmt_{snake(f['ref'])}_to_wire"
        o.append(f'{body}cJSON_AddStringToObject(obj, "{w}", {fn}(value->{n}));')
    elif kind == "model":
        o.append(f"{body}cJSON *sub = {model_prefix(f['ref'])}_build(value->{n});")
        o.append(f'{body}if (sub) cJSON_AddItemToObject(obj, "{w}", sub);')
    elif kind == "json_text":
        o.append(f"{body}cJSON *sub = cJSON_Parse(value->{n});")
        o.append(f'{body}if (sub) cJSON_AddItemToObject(obj, "{w}", sub);')
    elif kind == "string_array":
        o.append(f'{body}cJSON *arr = cJSON_AddArrayToObject(obj, "{w}");')
        o.append(f"{body}for (size_t i = 0; arr && i < value->{n}_count; i++)")
        o.append(f"{body}    cJSON_AddItemToArray(arr, cJSON_CreateString(value->{n}[i]));")
    elif kind == "model_array":
        o.append(f'{body}cJSON *arr = cJSON_AddArrayToObject(obj, "{w}");')
        o.append(f"{body}for (size_t i = 0; arr && i < value->{n}_count; i++) {{")
        o.append(f"{body}    cJSON *sub = {model_prefix(f['ref'])}_build(value->{n}[i]);")
        o.append(f"{body}    if (sub) cJSON_AddItemToArray(arr, sub);")
        o.append(f"{body}}}")
    o.append(f"{indent}}}")
    return o


def emit_models_source() -> str:
    """parse / free / build for every model, plus the page and list wrappers."""
    secrets = sensitive_map()
    out = [BANNER_C]
    out.append("")
    out.append("#include <stdlib.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "axiam/management_models.h"')
    out.append('#include "internal.h"')
    out.append('#include "management_internal.h"')
    out.append("")

    # ---- enum conversions ----
    for name in schema_closure():
        rendered = pascal(name)
        if rendered not in ENUMS:
            continue
        values = [str(v) for v in ((SCHEMAS.get(name) or {}).get("enum") or [])]
        if not values:
            continue
        s = snake(rendered)
        out.append(f"int axiam_mgmt_{s}_from_wire(const char *value, axiam_mgmt_{s}_t *out) {{")
        out.append("    if (!value || !out) return -1;")
        for v in values:
            out.append(f'    if (strcmp(value, "{v}") == 0) {{ *out = {enum_const(rendered, v)}; return 0; }}')
        out.extend(comment(
            "\u00a727.11 rule 1: an unrecognised value decodes, it does not fail. Reporting it "
            "here would make the caller drop the whole record over one field it did not "
            "ask about. It is still never read as one of the KNOWN constants -- that "
            "would turn a new server state into a wrong one, and on this surface these "
            "values gate access.",
            "    "))
        out.append(f"    *out = {enum_const(rendered, 'unknown')};")
        out.append("    return 0;")
        out.append("}")
        out.append("")
        out.append(f"const char *axiam_mgmt_{s}_to_wire(axiam_mgmt_{s}_t value) {{")
        out.append("    switch (value) {")
        for v in values:
            out.append(f'        case {enum_const(rendered, v)}: return "{v}";')
        out.extend(comment(
            "The empty string, which no server value is: an unrecognised value carried "
            "back into an update is refused by the server rather than written as a "
            "spelling it never used.", "        "))
        out.append(f'        case {enum_const(rendered, "unknown")}: return "";')
        out.append("    }")
        out.append(f'    return "{values[0]}";')
        out.append("}")
        out.append("")

    # ---- forward declarations for parse/build ----
    modelled = []
    for name in schema_closure():
        rendered = pascal(name)
        if rendered in ENUMS:
            continue
        fields, _ = fields_of(name, secrets.get(name, set()))
        if fields:
            modelled.append((name, rendered, fields))

    out.extend(comment("Internal parse/build, declared up front because models are mutually recursive."))
    for _, rendered, _ in modelled:
        out.append(f"{model_type(rendered)} *{model_prefix(rendered)}_parse(const cJSON *src);")
        out.append(f"cJSON *{model_prefix(rendered)}_build(const {model_type(rendered)} *value);")
    out.append("")

    for name, rendered, fields in modelled:
        for f in fields:
            f["owner"] = rendered

        # free
        out.append(f"void {model_prefix(rendered)}_free({model_type(rendered)} *value) {{")
        out.append("    if (!value) return;")
        for f in fields:
            out.extend(emit_free_field(f))
        out.append("    free(value);")
        out.append("}")
        out.append("")

        # parse
        out.append(f"{model_type(rendered)} *{model_prefix(rendered)}_parse(const cJSON *src) {{")
        out.append("    if (!cJSON_IsObject(src)) return NULL;")
        out.append(f"    {model_type(rendered)} *out = ({model_type(rendered)} *) "
                   f"calloc(1, sizeof(*out));")
        out.append("    if (!out) return NULL;")
        out.append("    const cJSON *item;")
        out.append("    (void) item;")
        for f in fields:
            out.extend(emit_parse_field(f))
        out.append("    return out;")
        out.append("}")
        out.append("")

        # build
        out.append(f"cJSON *{model_prefix(rendered)}_build(const {model_type(rendered)} *value) {{")
        out.append("    if (!value) return NULL;")
        if any(f["kind"] == "union_raw" for f in fields):
            out.extend(comment(
                "A union is forwarded EXACTLY as received. Re-encoding from the two "
                "members this SDK models would drop every field belonging to the variant "
                "it does not model -- and the server round-trips those.", "    "))
            out.append("    if (value->raw) return cJSON_Parse(value->raw);")
        out.append("    cJSON *obj = cJSON_CreateObject();")
        out.append("    if (!obj) return NULL;")
        for f in fields:
            out.extend(emit_build_field(f))
        out.append("    return obj;")
        out.append("}")
        out.append("")

    # ---- page / list frees ----
    for name in paginated_models():
        s = snake(name)
        out.append(f"void axiam_mgmt_{s}_page_free(axiam_mgmt_{s}_page_t *page) {{")
        out.append("    if (!page) return;")
        out.append("    if (page->items) {")
        out.append(f"        for (size_t i = 0; i < page->count; i++) {model_prefix(name)}_free(page->items[i]);")
        out.append("        free(page->items);")
        out.append("    }")
        out.append("    free(page);")
        out.append("}")
        out.append("")

    for name in array_models():
        s = snake(name)
        out.append(f"void axiam_mgmt_{s}_list_free(axiam_mgmt_{s}_list_t *list) {{")
        out.append("    if (!list) return;")
        out.append("    if (list->items) {")
        out.append(f"        for (size_t i = 0; i < list->count; i++) {model_prefix(name)}_free(list->items[i]);")
        out.append("        free(list->items);")
        out.append("    }")
        out.append("    free(list);")
        out.append("}")
        out.append("")

    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Operations (27.3 flat symbols)
# ---------------------------------------------------------------------------


def op_symbol(namespace: str, opname: str) -> str:
    """The flat C name for one operation.

    `axiam_<namespace>_<operation>`, which is the exact shape CONTRACT.md 27.3's
    per-language table gives C -- its row reads
    `axiam_service_accounts_rotate_secret(client, id, &out)`. The namespace lives in the
    NAME rather than in a receiver, and sorted alphabetically a completion list groups
    exactly the way handles do in the SDKs that have them.

    Deliberately NOT `axiam_mgmt_<ns>_<op>`: an extra segment would be this SDK's own
    invention in the one place 27.3 spells the symbol out. The MODEL types below keep
    the `axiam_mgmt_` prefix, because 27.3 governs the operation accessor and says
    nothing about type names -- and there the prefix earns its keep by separating 145
    generated types from the SDK's own.
    """
    return f"axiam_{cname(namespace)}_{cname(opname)}"


def path_params(op: dict[str, Any]) -> list[str]:
    return re.findall(r"\{([^}]+)\}", op["path"])


def implicit_of(namespace: str, op: dict[str, Any]) -> set[str]:
    """Which path parameters the SDK fills in from the client (27.4 rule 3)."""
    names = set(path_params(op))
    implicit = {"org_id"} & names
    if "tenant_id" in names and namespace in IMPLICIT_TENANT_NAMESPACES:
        implicit.add("tenant_id")
    return implicit


def op_params(namespace: str, op: dict[str, Any]) -> list[dict[str, str]]:
    """The C parameter list for one operation, in declaration order."""
    implicit = implicit_of(namespace, op)
    params: list[dict[str, str]] = []

    if implicit:
        params.append({
            "name": "scope", "decl": "const axiam_mgmt_call_scope_t *", "kind": "scope",
            "wire": "",
            "text": "Per-call `{org_id}`/`{tenant_id}` override, or NULL for the client's "
                    "own (27.4 rule 3).",
        })

    for name in path_params(op):
        if name in implicit:
            continue
        params.append({
            "name": cname(name), "decl": "const char *", "kind": "path", "wire": name,
            "text": f"The `{{{name}}}` path parameter.",
        })

    for q in op["query_params"]:
        # `search` rides on axiam_mgmt_page_req_t with `offset`/`limit` (\u00a727.4 rule 4),
        # not as a separate argument -- otherwise axiam_mgmt_page_next() has no way to
        # carry it past the first request of a walk.
        if op["paginated"] and q["name"] in {"offset", "limit", "search"}:
            continue
        params.append({
            "name": cname(q["name"]), "decl": "const char *", "kind": "query",
            "wire": q["name"],
            "text": f"The `{q['name']}` query parameter"
                    + ("." if q["required"] else ", or NULL to omit it."),
        })

    if op["request_body"] != "none" and op["request_schema"]:
        model = pascal(op["request_schema"].lstrip("[]"))
        params.append({
            "name": "body", "decl": f"const {model_type(model)} *", "kind": "body",
            "wire": "", "text": "The request body.",
        })

    if op["paginated"]:
        params.append({
            "name": "page", "decl": "const axiam_mgmt_page_req_t *", "kind": "page",
            "wire": "", "text": "Which page to fetch, or NULL for the first at the default size.",
        })

    kind = op["response"]["kind"]
    schema = op["response"]["schema"]
    if kind != "none" and schema:
        model = pascal(schema.lstrip("[]"))
        if kind == "page":
            decl = f"axiam_mgmt_{snake(model)}_page_t **"
            text = (f"Receives the page on success; free with "
                    f"axiam_mgmt_{snake(model)}_page_free(). Set to NULL on failure.")
        elif kind == "array":
            decl = f"axiam_mgmt_{snake(model)}_list_t **"
            text = (f"Receives the list on success; free with "
                    f"axiam_mgmt_{snake(model)}_list_free(). Set to NULL on failure.")
        else:
            decl = f"{model_type(model)} **"
            text = (f"Receives the object on success; free with "
                    f"{model_prefix(model)}_free(). Set to NULL on failure.")
        params.append({"name": "out", "decl": decl, "kind": "out", "wire": "", "text": text})

    params.append({
        "name": "err", "decl": "axiam_error_t *", "kind": "err", "wire": "",
        "text": "Filled on failure; may be NULL.",
    })
    return params


def op_signature(namespace: str, opname: str, op: dict[str, Any]) -> str:
    """The full declaration, minus the trailing `;` or ` {`."""
    params = op_params(namespace, op)
    args = ["axiam_client_t *c"] + [f"{p['decl']}{p['name']}" for p in params]
    return f"axiam_error_kind_t {op_symbol(namespace, opname)}({', '.join(args)})"


def op_doc(namespace: str, opname: str, op: dict[str, Any]) -> str:
    """The Doxygen summary for one operation."""
    entry = (SPEC.get("paths") or {}).get(op["path"]) or {}
    node = entry.get(op["method"].lower()) or {}
    described = node.get("summary") or node.get("description")

    lead = f"`{op['method']} {op['path']}`."
    if described:
        lead = f"{escape(described)}\n\n`{op['method']} {op['path']}`."

    kind = op["response"]["kind"]
    if kind == "page":
        lead += ("\n\nReturns ONE page. `total` on it is the server's count across all "
                 "pages and is not `count` -- see 27.4 rule 4.")
    elif kind == "array":
        lead += ("\n\nReturns the server's complete list. This endpoint is NOT paginated, "
                 "so the result is a plain list and never a page (27.4 rule 4).")
    elif kind == "none":
        lead += "\n\nReturns nothing; the server answers with an empty body."

    if op["method"] == "DELETE":
        lead += ("\n\nNOT idempotent (27.4 rule 6): deleting something already deleted "
                 "fails with AXIAM_MGMT_ERR_NOT_FOUND rather than succeeding quietly.")
    if op["sensitive_response_fields"]:
        fields = ", ".join(f"`{f}`" for f in op["sensitive_response_fields"])
        lead += (f"\n\nThe response carries a ONE-TIME secret ({fields}): the server will "
                 "not return it again, so a caller that does not persist it here cannot "
                 "recover it (27.5).")
    return lead


def emit_ops_header() -> str:
    """The 146 flat operation declarations."""
    out = [BANNER_C, ""]
    out.append("#ifndef AXIAM_MANAGEMENT_OPS_H")
    out.append("#define AXIAM_MANAGEMENT_OPS_H")
    out.append("")
    out.append('#include "axiam/management.h"')
    out.append('#include "axiam/management_models.h"')
    out.append("")
    out.append("#ifdef __cplusplus")
    out.append('extern "C" {')
    out.append("#endif")
    out.append("")

    for namespace, nsdef in REGISTRY["namespaces"].items():
        out.extend(comment("=" * 76))
        out.extend(comment(f"{namespace} -- {nsdef['doc']}"))
        out.extend(comment("=" * 76))
        out.append("")
        for opname, op in nsdef["operations"].items():
            tags = [f"@param c The client. Must have an active session (27.4 rule 1)."]
            tags += [f"@param {p['name']} {p['text']}" for p in op_params(namespace, op)]
            tags.append("@return AXIAM_OK on success, or the failing kind.")
            block = doc(op_doc(namespace, opname, op))
            block = block[:-1] + [" *"] + [f" * {t}" for t in tags] + [" */"]
            out.extend(block)
            out.append(op_signature(namespace, opname, op) + ";")
            out.append("")

    out.append("#ifdef __cplusplus")
    out.append("}")
    out.append("#endif")
    out.append("")
    out.append("#endif /* AXIAM_MANAGEMENT_OPS_H */")
    return "\n".join(out) + "\n"


def emit_ops_source() -> str:
    """The 146 operation bodies. Every one funnels through axiam_mgmt_send() (27.8)."""
    out = [BANNER_C, ""]
    out.append("#include <stdlib.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "axiam/management_ops.h"')
    out.append('#include "internal.h"')
    out.append('#include "management_internal.h"')
    out.append("")
    out.extend(comment(
        "Internal parse/build, shared with management_models.c. Declared rather than "
        "made public: a caller has the typed operations above and never needs to hand a "
        "raw cJSON to a model."))
    secrets = sensitive_map()
    modelled = []
    for name in schema_closure():
        rendered = pascal(name)
        if rendered in ENUMS:
            continue
        if fields_of(name, secrets.get(name, set()))[0]:
            modelled.append(rendered)
    for rendered in modelled:
        out.append(f"{model_type(rendered)} *{model_prefix(rendered)}_parse(const cJSON *src);")
        out.append(f"cJSON *{model_prefix(rendered)}_build(const {model_type(rendered)} *value);")
    out.append("")

    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            out.extend(emit_op_body(namespace, opname, op))
            out.append("")

    return "\n".join(out) + "\n"


def emit_op_body(namespace: str, opname: str, op: dict[str, Any]) -> list[str]:
    """One operation implementation."""
    params = op_params(namespace, op)
    implicit = implicit_of(namespace, op)
    canonical = f"{namespace}.{opname}"
    kind = op["response"]["kind"]
    schema = op["response"]["schema"]
    model = pascal(schema.lstrip("[]")) if schema else ""

    out = [op_signature(namespace, opname, op) + " {"]
    has_out = any(p["kind"] == "out" for p in params)
    if has_out:
        out.append("    if (out) *out = NULL;")

    # ---- path ----
    names = path_params(op)
    if names:
        out.append(f"    const char *path_names[{len(names)}];")
        out.append(f"    const char *path_values[{len(names)}];")
        for i, name in enumerate(names):
            out.append(f'    path_names[{i}] = "{name}";')
            if name == "org_id" and name in implicit:
                out.append(f"    path_values[{i}] = axiam_mgmt_resolved_org_id(c, scope);")
            elif name == "tenant_id" and name in implicit:
                out.append(f"    path_values[{i}] = axiam_mgmt_resolved_tenant_id(c, scope);")
            else:
                out.append(f"    path_values[{i}] = {cname(name)};")
        out.append(f'    char *path = axiam_mgmt_path("{op["path"]}", path_names, path_values, {len(names)});')
    else:
        out.append(f'    char *path = axiam_mgmt_path("{op["path"]}", NULL, NULL, 0);')

    out.append("    if (!path) {")
    if implicit:
        out.extend(comment(
            "A NULL path means an identifier was missing -- almost always the implicit "
            "org/tenant id on a client that was never given one. Reporting it names what "
            "to fix; sending an empty path segment would surface as an undiagnosable 404.",
            "        "))
        out.append(f'        axiam_error_set(err, AXIAM_ERR_NETWORK, 0, "{canonical}: '
                   f'missing an organization or tenant id -- configure one on the client '
                   f'or pass a scope (27.4 rule 3)");')
    else:
        out.append(f'        axiam_error_set(err, AXIAM_ERR_NETWORK, 0, "{canonical}: '
                   f'could not build the request path");')
    out.append("        return AXIAM_ERR_NETWORK;")
    out.append("    }")

    # ---- query ----
    queries = [p for p in params if p["kind"] == "query"]
    if op["paginated"] or queries:
        count = len(queries) + (3 if op["paginated"] else 0)
        out.append(f"    const char *q_names[{count}];")
        out.append(f"    const char *q_values[{count}];")
        idx = 0
        if op["paginated"]:
            out.append("    char offset_buf[24], limit_buf[24];")
            out.append("    axiam_mgmt_page_query(page, offset_buf, limit_buf);")
            out.append(f'    q_names[{idx}] = "offset"; q_values[{idx}] = offset_buf;')
            idx += 1
            out.append(f'    q_names[{idx}] = "limit"; q_values[{idx}] = limit_buf;')
            idx += 1
            # A NULL value is OMITTED by axiam_mgmt_query, which is what makes an unset
            # or blank term send no `search` key at all (§27.4 rule 4).
            out.append(f'    q_names[{idx}] = "search";')
            out.append(f'    q_values[{idx}] = page ? axiam_mgmt_page_search(page->search) : NULL;')
            idx += 1
        for p in queries:
            out.append(f'    q_names[{idx}] = "{p["wire"]}"; q_values[{idx}] = {p["name"]};')
            idx += 1
        out.append(f"    path = axiam_mgmt_query(path, q_names, q_values, {count});")
        out.append("    if (!path) {")
        out.append(f'        axiam_error_set(err, AXIAM_ERR_NETWORK, 0, "{canonical}: out of memory");')
        out.append("        return AXIAM_ERR_NETWORK;")
        out.append("    }")

    # ---- body ----
    body_param = next((p for p in params if p["kind"] == "body"), None)
    if body_param:
        bmodel = pascal(op["request_schema"].lstrip("[]"))
        out.append(f"    char *body_json = axiam_mgmt_render({model_prefix(bmodel)}_build(body));")
    else:
        out.append("    char *body_json = NULL;")

    # ---- send ----
    out.append("    cJSON *json = NULL;")
    out.append("    axiam_error_kind_t rc = axiam_mgmt_send(")
    out.append(f'        c, "{canonical}", "{op["method"]}", "{op["path"]}", path, body_json,')
    out.append("        &json, err);")
    out.append("    free(path);")
    out.append("    free(body_json);")
    out.append("    if (rc != AXIAM_OK) return rc;")

    # ---- decode ----
    if kind == "none" or not schema:
        out.append("    cJSON_Delete(json);")
        out.append("    return AXIAM_OK;")
    elif kind == "page":
        s = snake(model)
        out.append(f"    axiam_mgmt_{s}_page_t *result = (axiam_mgmt_{s}_page_t *) calloc(1, sizeof(*result));")
        out.append("    if (!result) { cJSON_Delete(json); return AXIAM_ERR_NETWORK; }")
        out.append("    const cJSON *items = axiam_mgmt_page_items(json);")
        out.append("    size_t n = items ? (size_t) cJSON_GetArraySize(items) : 0;")
        out.append("    if (n > 0) {")
        out.append(f"        result->items = ({model_type(model)} **) calloc(n, sizeof({model_type(model)} *));")
        out.append(f"        if (!result->items) {{ axiam_mgmt_{s}_page_free(result); cJSON_Delete(json); return AXIAM_ERR_NETWORK; }}")
        out.append("        for (size_t i = 0; i < n; i++)")
        out.append(f"            result->items[i] = {model_prefix(model)}_parse(cJSON_GetArrayItem((cJSON *) items, (int) i));")
        out.append("        result->count = n;")
        out.append("    }")
        out.append("    result->total = axiam_mgmt_page_total(json, (long) n);")
        out.append("    result->request = page ? *page : (axiam_mgmt_page_req_t) { 0, AXIAM_MGMT_DEFAULT_LIMIT, NULL };")
        out.append("    cJSON_Delete(json);")
        out.append("    if (out) *out = result;")
        out.append(f"    else axiam_mgmt_{s}_page_free(result);")
        out.append("    return AXIAM_OK;")
    elif kind == "array":
        s = snake(model)
        out.append(f"    axiam_mgmt_{s}_list_t *result = (axiam_mgmt_{s}_list_t *) calloc(1, sizeof(*result));")
        out.append("    if (!result) { cJSON_Delete(json); return AXIAM_ERR_NETWORK; }")
        out.append("    size_t n = cJSON_IsArray(json) ? (size_t) cJSON_GetArraySize(json) : 0;")
        out.append("    if (n > 0) {")
        out.append(f"        result->items = ({model_type(model)} **) calloc(n, sizeof({model_type(model)} *));")
        out.append(f"        if (!result->items) {{ axiam_mgmt_{s}_list_free(result); cJSON_Delete(json); return AXIAM_ERR_NETWORK; }}")
        out.append("        for (size_t i = 0; i < n; i++)")
        out.append(f"            result->items[i] = {model_prefix(model)}_parse(cJSON_GetArrayItem(json, (int) i));")
        out.append("        result->count = n;")
        out.append("    }")
        out.append("    cJSON_Delete(json);")
        out.append("    if (out) *out = result;")
        out.append(f"    else axiam_mgmt_{s}_list_free(result);")
        out.append("    return AXIAM_OK;")
    else:
        out.append(f"    {model_type(model)} *result = {model_prefix(model)}_parse(json);")
        out.append("    cJSON_Delete(json);")
        out.append("    if (!result) {")
        out.append(f'        axiam_error_set(err, AXIAM_ERR_NETWORK, 0, "{canonical}: '
                   f'the response body was not the expected object");')
        out.append("        return AXIAM_ERR_NETWORK;")
        out.append("    }")
        out.append("    if (out) *out = result;")
        out.append(f"    else {model_prefix(model)}_free(result);")
        out.append("    return AXIAM_OK;")

    out.append("}")
    return out


# ---------------------------------------------------------------------------
# Generated conformance test
# ---------------------------------------------------------------------------


def example_json(schema: Any, depth: int = 0) -> Any:
    """A plausible wire value for ``schema`` -- what the fake transport returns."""
    if depth > 6 or not isinstance(schema, dict):
        return None
    if "$ref" in schema:
        return example_for(schema["$ref"].split("/")[-1], depth + 1)
    inner = nullable_ref(schema)
    if inner:
        return example_for(inner, depth + 1)
    if isinstance(schema.get("allOf"), list) and len(schema["allOf"]) == 1:
        return example_json(schema["allOf"][0], depth)
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)
    if kind == "array":
        return [example_json(schema.get("items") or {}, depth + 1)]
    if kind == "integer":
        return 1
    if kind == "number":
        return 1.5
    if kind == "boolean":
        return True
    if kind == "string":
        fmt = schema.get("format")
        if fmt == "uuid":
            return EXAMPLE_UUID
        if fmt == "date-time":
            return EXAMPLE_TIME
        return "example"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        return {k: example_json(v, depth + 1) for k, v in (schema.get("properties") or {}).items()}
    return {}


def example_for(name: str, depth: int = 0) -> Any:
    """A plausible wire object for the named schema."""
    if depth > 6:
        return None
    schema = SCHEMAS.get(name) or {}
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    props, _, _ = flatten(name)
    return {k: example_json(v, depth + 1) for k, v in props.items()}


def example_required_only(name: str) -> Any:
    """A wire object carrying ONLY the required fields of ``name``.

    The mirror of example_for(). Together they exercise both arms of every optional
    field's parse guard: the full object proves a field survives the round trip, and this
    one proves the model copes when the server omits it -- which is the case a real server
    produces constantly and the one a fixture built from a complete example never reaches.
    """
    schema = SCHEMAS.get(name) or {}
    if discriminated(schema):
        return None
    props, required, _ = flatten(name)
    return {k: example_json(v, 1) for k, v in props.items() if k in required}

def example_response(op: dict[str, Any]) -> Any:
    """The body the fake transport returns, honouring ``response.kind``.

    Reads ``response.kind`` and never infers plurality from the schema NAME. The
    registry's ``response.schema`` carries no ``[]`` prefix, so a generator guessing from
    the name types all 13 bare-array reads as single objects.
    """
    kind = op["response"]["kind"]
    schema = op["response"]["schema"]
    if kind == "none" or not schema:
        return None
    body = example_for(schema.lstrip("[]"))
    if kind == "page":
        return {"items": [body], "total": 1, "offset": 0, "limit": 50}
    if kind == "array":
        return [body]
    return body


def c_string(text: str) -> str:
    """A C string literal for ``text``."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def expected_path(op: dict[str, Any]) -> str:
    return re.sub(r"\{[^}]+\}", EXAMPLE_UUID, op["path"])


def emit_test() -> str:
    """One conformance case per operation: right method, right path, freed cleanly."""
    out = [BANNER_C, ""]
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "unity.h"')
    out.append('#include "axiam/axiam.h"')
    out.append('#include "axiam/management_ops.h"')
    out.append('#include "test_util.h"')
    out.append('#include "management_test_util.h"')
    out.append("")
    out.extend(comment(
        "One case per CONTRACT.md 27 operation -- all 146 of them.\n\n"
        "Each asserts that the operation issues the METHOD the registry names against the "
        "PATH the registry names, and that whatever it allocated frees cleanly (the suite "
        "runs under ASan/UBSan in CI, so a leak or a double free fails here rather than in "
        "somebody's daemon).\n\n"
        "Generated by scripts/gen_management.py; CI re-runs it with --check."))
    out.append("")

    cases = []
    extra_cases: list[str] = []
    count = 0
    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            count += 1
            params = op_params(namespace, op)
            body = example_response(op)
            fn = f"test_{cname(namespace)}_{cname(opname)}_reaches_its_route"

            block = [f"static void {fn}(void) {{"]
            if body is None:
                block.append("    mgmt_mount(204, NULL);")
            else:
                block.append(f"    mgmt_mount(200, {c_string(json.dumps(body))});")
            block.append("    axiam_client_t *c = mgmt_signed_in_client();")
            block.append("    axiam_error_t err;")

            args = ["c"]
            frees = []
            for p in params:
                if p["kind"] == "scope":
                    args.append("NULL")
                elif p["kind"] == "path":
                    args.append(f'"{EXAMPLE_UUID}"')
                elif p["kind"] == "query":
                    args.append("NULL")
                elif p["kind"] == "body":
                    bmodel = pascal(op["request_schema"].lstrip("[]"))
                    block.append(f"    {model_type(bmodel)} body;")
                    block.append("    memset(&body, 0, sizeof(body));")
                    args.append("&body")
                elif p["kind"] == "page":
                    args.append("NULL")
                elif p["kind"] == "out":
                    decl = p["decl"].rstrip(" *")
                    block.append(f"    {decl} *result = NULL;")
                    args.append("&result")
                    kind = op["response"]["kind"]
                    m = snake(pascal(op["response"]["schema"].lstrip("[]")))
                    if kind == "page":
                        frees.append(f"axiam_mgmt_{m}_page_free(result);")
                    elif kind == "array":
                        frees.append(f"axiam_mgmt_{m}_list_free(result);")
                    else:
                        frees.append(f"axiam_mgmt_{m}_free(result);")
                elif p["kind"] == "err":
                    args.append("&err")

            block.append(f"    axiam_error_kind_t rc = {op_symbol(namespace, opname)}("
                         + ", ".join(args) + ");")
            block.append("")
            block.append("    TEST_ASSERT_EQUAL_INT(AXIAM_OK, rc);")
            block.append(f'    TEST_ASSERT_EQUAL_STRING("{op["method"]}", mgmt_last_method());')
            block.append(f'    TEST_ASSERT_EQUAL_STRING("{expected_path(op)}", mgmt_last_path());')
            for free in frees:
                block.append(f"    {free}")
            block.append("    axiam_client_free(c);")
            block.append("}")
            cases.append("\n".join(block))

            # A second case: out == NULL. Passing NULL for the result pointer is a
            # documented way to say "issue this, I do not need the object" -- and it is
            # the arm where the operation must FREE what it parsed rather than leak it.
            # Under ASan this case is the leak assertion for that path.
            if any(p["kind"] == "out" for p in params):
                discard = [f"static void {fn}_discards_the_result(void) {{"]
                if body is None:
                    discard.append("    mgmt_mount(204, NULL);")
                else:
                    discard.append(f"    mgmt_mount(200, {c_string(json.dumps(body))});")
                discard.append("    axiam_client_t *c = mgmt_signed_in_client();")
                discard.append("    axiam_error_t err;")
                discard_args = []
                for p in params:
                    if p["kind"] == "scope":
                        discard_args.append("NULL")
                    elif p["kind"] == "path":
                        discard_args.append(f'"{EXAMPLE_UUID}"')
                    elif p["kind"] == "query":
                        discard_args.append("NULL")
                    elif p["kind"] == "body":
                        bmodel = pascal(op["request_schema"].lstrip("[]"))
                        discard.append(f"    {model_type(bmodel)} body;")
                        discard.append("    memset(&body, 0, sizeof(body));")
                        discard_args.append("&body")
                    elif p["kind"] == "page":
                        discard_args.append("NULL")
                    elif p["kind"] == "out":
                        discard_args.append("NULL")
                    elif p["kind"] == "err":
                        discard_args.append("&err")
                discard.append(f"    axiam_error_kind_t rc = {op_symbol(namespace, opname)}(c, "
                               + ", ".join(discard_args) + ");")
                discard.append("")
                discard.append("    TEST_ASSERT_EQUAL_INT(AXIAM_OK, rc);")
                discard.append("    axiam_client_free(c);")
                discard.append("}")
                cases.append("\n".join(discard))
                extra_cases.append(f"{fn}_discards_the_result")

            # A third case for the object-returning operations: a 200 whose body is the
            # WRONG JSON SHAPE. A server that answers a single-object route with an array
            # is not a hypothetical -- a proxy that collapses a collection, or a route
            # that changed shape -- and the operation must report it rather than hand back
            # a model parsed from nothing.
            if op["response"]["kind"] == "object" and op["response"]["schema"]:
                shape = [f"static void {fn}_rejects_a_wrong_shaped_body(void) {{"]
                shape.append('    mgmt_mount(200, "[]");')
                shape.append("    axiam_client_t *c = mgmt_signed_in_client();")
                shape.append("    axiam_error_t err;")
                shape_args = []
                for p in params:
                    if p["kind"] == "scope":
                        shape_args.append("NULL")
                    elif p["kind"] == "path":
                        shape_args.append(f'"{EXAMPLE_UUID}"')
                    elif p["kind"] == "query":
                        shape_args.append("NULL")
                    elif p["kind"] == "body":
                        bmodel = pascal(op["request_schema"].lstrip("[]"))
                        shape.append(f"    {model_type(bmodel)} body;")
                        shape.append("    memset(&body, 0, sizeof(body));")
                        shape_args.append("&body")
                    elif p["kind"] == "page":
                        shape_args.append("NULL")
                    elif p["kind"] == "out":
                        decl = p["decl"].rstrip(" *")
                        shape.append(f"    {decl} *result = NULL;")
                        shape_args.append("&result")
                    elif p["kind"] == "err":
                        shape_args.append("&err")
                shape.append(f"    axiam_error_kind_t rc = {op_symbol(namespace, opname)}(c, "
                             + ", ".join(shape_args) + ");")
                shape.append("")
                shape.append("    TEST_ASSERT_EQUAL_INT(AXIAM_ERR_NETWORK, rc);")
                shape.append("    TEST_ASSERT_NULL(result);")
                shape.append("    axiam_client_free(c);")
                shape.append("}")
                cases.append("\n".join(shape))
                extra_cases.append(f"{fn}_rejects_a_wrong_shaped_body")

            # A fourth case, for the routes that substitute an implicit id: a client with
            # neither an org nor a tenant id must REFUSE rather than send an empty path
            # segment, which the server answers as an undiagnosable 404.
            if implicit_of(namespace, op):
                unscoped = [f"static void {fn}_refuses_without_a_scope(void) {{"]
                unscoped.append("    axiam_client_t *c = mgmt_unscoped_client();")
                unscoped.append("    axiam_error_t err;")
                unscoped_args = []
                for p in params:
                    if p["kind"] == "scope":
                        unscoped_args.append("NULL")
                    elif p["kind"] == "path":
                        unscoped_args.append(f'"{EXAMPLE_UUID}"')
                    elif p["kind"] == "query":
                        unscoped_args.append("NULL")
                    elif p["kind"] == "body":
                        bmodel = pascal(op["request_schema"].lstrip("[]"))
                        unscoped.append(f"    {model_type(bmodel)} body;")
                        unscoped.append("    memset(&body, 0, sizeof(body));")
                        unscoped_args.append("&body")
                    elif p["kind"] == "page":
                        unscoped_args.append("NULL")
                    elif p["kind"] == "out":
                        unscoped_args.append("NULL")
                    elif p["kind"] == "err":
                        unscoped_args.append("&err")
                unscoped.append(f"    axiam_error_kind_t rc = {op_symbol(namespace, opname)}(c, "
                                + ", ".join(unscoped_args) + ");")
                unscoped.append("")
                unscoped.append("    TEST_ASSERT_EQUAL_INT(AXIAM_ERR_NETWORK, rc);")
                unscoped.extend(comment(
                    "1, not 0: the login itself is a request. What matters is that NO "
                    "management request followed it.", "    "))
                unscoped.append("    TEST_ASSERT_EQUAL_INT(1, mgmt_request_count());")
                unscoped.append("    axiam_client_free(c);")
                unscoped.append("}")
                cases.append("\n".join(unscoped))
                extra_cases.append(f"{fn}_refuses_without_a_scope")

    out.append("\n\n".join(cases))
    out.append("")
    out.append("void setUp(void) { mgmt_reset(); }")
    out.append("void tearDown(void) {}")
    out.append("")
    out.extend(comment(
        "27.9: the registry's own operation count is asserted here, so an operation "
        "silently dropped by a bad regeneration fails the build rather than quietly "
        "reducing what is covered."))
    out.append("static void test_every_registry_operation_has_a_case(void) {")
    out.append(f"    TEST_ASSERT_EQUAL_INT({count}, mgmt_case_count());")
    out.append("}")
    out.append("")
    out.append("int main(void) {")
    out.append("    UNITY_BEGIN();")
    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname in nsdef["operations"]:
            out.append(f"    RUN_TEST(test_{cname(namespace)}_{cname(opname)}_reaches_its_route);")
    for extra in extra_cases:
        out.append(f"    RUN_TEST({extra});")
    out.append("    RUN_TEST(test_every_registry_operation_has_a_case);")
    out.append("    return UNITY_END();")
    out.append("}")
    out.append("")
    out.extend(comment("How many cases this file declares -- read by the assertion above."))
    out.append(f"int mgmt_case_count(void) {{ return {count}; }}")
    return "\n".join(out) + "\n"


def emit_model_test() -> str:
    """One round-trip case per model: parse a full wire object, build it back, free it.

    This is what covers the OPTIONAL half of every model. The surface test next door
    decodes each operation's response, but a response fixture only exercises the fields
    that operation returns, and a request fixture sets required fields only -- so most of
    a 145-model surface's parse/build arms went unexecuted.

    Round-tripping a FULL object reaches them as a consequence of asserting something
    worth asserting: a model that can parse a field but not build it again is a silent
    one-way door, and in C the free() path that never runs is the one that turns out to
    leak. The suite runs under ASan/LSan in CI, so each case is also a leak assertion.
    """
    out = [BANNER_C, ""]
    out.append("#include <stdlib.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "unity.h"')
    out.append('#include "axiam/axiam.h"')
    out.append('#include "axiam/management_models.h"')
    out.append('#include "cJSON.h"')
    out.append("")
    out.extend(comment(
        "Round-trip coverage for every 27 model. Generated by scripts/gen_management.py; "
        "CI re-runs it with --check."))
    out.append("")
    out.extend(comment(
        "The generated parse/build pair is internal -- a caller has the typed operations "
        "and never hands a raw cJSON to a model -- so this test declares them itself "
        "rather than the header exposing them for a test's benefit."))
    secrets = sensitive_map()
    modelled = []
    for name in schema_closure():
        rendered = pascal(name)
        if rendered in ENUMS:
            continue
        if fields_of(name, secrets.get(name, set()))[0]:
            modelled.append((name, rendered))
    for _, rendered in modelled:
        out.append(f"{model_type(rendered)} *{model_prefix(rendered)}_parse(const cJSON *src);")
        out.append(f"cJSON *{model_prefix(rendered)}_build(const {model_type(rendered)} *value);")
    out.append("")
    out.append("void setUp(void) {}")
    out.append("void tearDown(void) {}")
    out.append("")

    count = 0
    for name, rendered in modelled:
        example = example_for(name)
        if not isinstance(example, dict) or not example:
            continue
        count += 1
        fn = f"test_{snake(rendered)}_round_trips"
        out.extend(comment(f"`{rendered}`: a full wire object parses, builds back and frees."))
        out.append(f"static void {fn}(void) {{")
        out.append(f"    cJSON *src = cJSON_Parse({c_string(json.dumps(example))});")
        out.append("    TEST_ASSERT_NOT_NULL(src);")
        out.append("")
        out.append(f"    {model_type(rendered)} *model = {model_prefix(rendered)}_parse(src);")
        out.append("    TEST_ASSERT_NOT_NULL(model);")
        out.append("")
        out.append(f"    cJSON *rebuilt = {model_prefix(rendered)}_build(model);")
        out.append("    TEST_ASSERT_NOT_NULL(rebuilt);")
        out.extend(comment(
            "Every key the server sent must survive parse AND build. A field the model "
            "can read but not write again is data it silently loses on anything the SDK "
            "re-sends.", "    "))
        out.append("    for (const cJSON *f = src->child; f; f = f->next) {")
        out.append("        if (cJSON_IsNull(f)) continue;")
        out.append("        TEST_ASSERT_NOT_NULL_MESSAGE(")
        out.append("            cJSON_GetObjectItemCaseSensitive(rebuilt, f->string), f->string);")
        out.append("    }")
        out.append("")
        out.append("    cJSON_Delete(rebuilt);")
        out.append(f"    {model_prefix(rendered)}_free(model);")
        out.append("    cJSON_Delete(src);")
        out.append("}")
        out.append("")

        minimal = example_required_only(name)
        if isinstance(minimal, dict) and minimal != example:
            out.extend(comment(
                f"`{rendered}`: the server omitting every OPTIONAL field is not an error."))
            out.append(f"static void test_{snake(rendered)}_parses_without_optionals(void) {{")
            out.append(f"    cJSON *src = cJSON_Parse({c_string(json.dumps(minimal))});")
            out.append("    TEST_ASSERT_NOT_NULL(src);")
            out.append("")
            out.append(f"    {model_type(rendered)} *model = {model_prefix(rendered)}_parse(src);")
            out.append("    TEST_ASSERT_NOT_NULL(model);")
            out.append("")
            out.extend(comment(
                "Building it back must not invent the fields that were absent: an unset "
                "member is OMITTED, not emitted as null (27.4 rule 5).", "    "))
            out.append(f"    cJSON *rebuilt = {model_prefix(rendered)}_build(model);")
            out.append("    TEST_ASSERT_NOT_NULL(rebuilt);")
            out.append("    for (const cJSON *f = rebuilt->child; f; f = f->next)")
            out.append("        TEST_ASSERT_FALSE_MESSAGE(cJSON_IsNull(f), f->string);")
            out.append("")
            out.append("    cJSON_Delete(rebuilt);")
            out.append(f"    {model_prefix(rendered)}_free(model);")
            out.append("    cJSON_Delete(src);")
            out.append("}")
            out.append("")

        out.extend(comment(
            f"`{rendered}`: an EMPTY object parses without crashing.\n\n"
            "A server that omits a field openapi.json marks required is malformed, and "
            "this SDK's answer is a model with that member unset rather than an abort -- "
            "the caller is in a position to decide, and a parser that segfaults on a bad "
            "response is a worse failure than one that hands back a null. This also "
            "reaches the ABSENT arm of every field guard, required ones included, which "
            "no well-formed fixture can."))
        out.append(f"static void test_{snake(rendered)}_parses_an_empty_object(void) {{")
        out.append('    cJSON *src = cJSON_Parse("{}");')
        out.append("    TEST_ASSERT_NOT_NULL(src);")
        out.append("")
        out.append(f"    {model_type(rendered)} *model = {model_prefix(rendered)}_parse(src);")
        out.append("    TEST_ASSERT_NOT_NULL(model);")
        out.append("")
        out.append(f"    cJSON *rebuilt = {model_prefix(rendered)}_build(model);")
        out.append("    if (rebuilt) cJSON_Delete(rebuilt);")
        out.append(f"    {model_prefix(rendered)}_free(model);")
        out.append("    cJSON_Delete(src);")
        out.append("}")
        out.append("")

        # Parsing something that is not an object must fail cleanly, not crash.
        out.append(f"static void test_{snake(rendered)}_rejects_a_non_object(void) {{")
        out.append("    cJSON *scalar = cJSON_CreateString(\"nope\");")
        out.append(f"    TEST_ASSERT_NULL({model_prefix(rendered)}_parse(scalar));")
        out.append(f"    {model_prefix(rendered)}_free(NULL);")
        out.append("    cJSON_Delete(scalar);")
        out.append("}")
        out.append("")

    out.append("int main(void) {")
    out.append("    UNITY_BEGIN();")
    for name, rendered in modelled:
        example = example_for(name)
        if not isinstance(example, dict) or not example:
            continue
        out.append(f"    RUN_TEST(test_{snake(rendered)}_round_trips);")
        minimal = example_required_only(name)
        if isinstance(minimal, dict) and minimal != example:
            out.append(f"    RUN_TEST(test_{snake(rendered)}_parses_without_optionals);")
        out.append(f"    RUN_TEST(test_{snake(rendered)}_parses_an_empty_object);")
        out.append(f"    RUN_TEST(test_{snake(rendered)}_rejects_a_non_object);")
    out.append("    return UNITY_END();")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_alloc_test() -> str:
    """An allocation-failure sweep over all 146 operations and every model.

    Every calloc/malloc in the generated surface is followed by a NULL check whose OOM
    arm never runs in an ordinary test, so gcovr reports it uncovered no matter how many
    happy-path tests exist. That is the same one-sided-guard problem tests/
    test_alloc_failures.c already solves for the rest of the SDK, and this file reuses its
    technique rather than inventing one: link-time --wrap of malloc/calloc/realloc, arm
    the Nth allocation to fail, drive a REAL call graph through it, and assert the
    function reports failure instead of crashing or double-freeing.

    Each operation is driven with every one of the first ALLOC_DEPTH allocations failed in
    turn. The assertion is not "it returned an error" -- some allocations happen after the
    point of no return -- but that it never crashes and never double-frees, which is what
    ASan and the wrap counter together check.
    """
    out = [BANNER_C, ""]
    out.append("#include <stdlib.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "unity.h"')
    out.append('#include "axiam/axiam.h"')
    out.append('#include "axiam/management_ops.h"')
    out.append('#include "cJSON.h"')
    out.append('#include "test_util.h"')
    out.append('#include "management_test_util.h"')
    out.append("")
    out.append("extern void *__real_malloc(size_t size);")
    out.append("extern void *__real_calloc(size_t nmemb, size_t size);")
    out.append("extern void *__real_realloc(void *ptr, size_t size);")
    out.append("")
    out.append("static long g_fail_at = -1;")
    out.append("static long g_call_count = 0;")
    out.append("")
    out.append("static int alloc_should_fail(void) {")
    out.append("    g_call_count++;")
    out.append("    if (g_fail_at > 0 && g_call_count == g_fail_at) {")
    out.append("        g_fail_at = -1; /* one-shot */")
    out.append("        return 1;")
    out.append("    }")
    out.append("    return 0;")
    out.append("}")
    out.append("")
    out.append("void *__wrap_malloc(size_t size) {")
    out.append("    if (alloc_should_fail()) return NULL;")
    out.append("    return __real_malloc(size);")
    out.append("}")
    out.append("")
    out.append("void *__wrap_calloc(size_t nmemb, size_t size) {")
    out.append("    if (alloc_should_fail()) return NULL;")
    out.append("    return __real_calloc(nmemb, size);")
    out.append("}")
    out.append("")
    out.append("void *__wrap_realloc(void *ptr, size_t size) {")
    out.append("    if (alloc_should_fail()) return NULL;")
    out.append("    return __real_realloc(ptr, size);")
    out.append("}")
    out.append("")
    out.append("static void arm(long n) { g_fail_at = n; g_call_count = 0; }")
    out.append("static void disarm(void) { g_fail_at = -1; g_call_count = 0; }")
    out.append("")
    out.append("void setUp(void) { disarm(); mgmt_reset(); }")
    out.append("void tearDown(void) { disarm(); }")
    out.append("")
    out.extend(comment(
        "How deep to push failure injection into each operation's call graph. Every "
        "generated operation allocates a path, optionally a query and a body, a result "
        "and its items -- comfortably inside this many."))
    out.append("#define ALLOC_DEPTH 24")
    out.append("")

    cases = []
    names = []
    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            params = op_params(namespace, op)
            body = example_response(op)
            fn = f"test_{cname(namespace)}_{cname(opname)}_survives_oom"
            names.append(fn)

            block = [f"static void {fn}(void) {{"]
            block.append("    for (long n = 1; n <= ALLOC_DEPTH; n++) {")
            block.append("        mgmt_reset();")
            if body is None:
                block.append("        mgmt_mount(204, NULL);")
            else:
                block.append(f"        mgmt_mount(200, {c_string(json.dumps(body))});")
            block.append("        axiam_client_t *c = mgmt_signed_in_client();")
            block.append("        if (!c) continue;")
            block.append("        axiam_error_t err;")

            args = ["c"]
            frees = []
            for p in params:
                if p["kind"] == "scope":
                    args.append("NULL")
                elif p["kind"] == "path":
                    args.append(f'"{EXAMPLE_UUID}"')
                elif p["kind"] == "query":
                    args.append("NULL")
                elif p["kind"] == "body":
                    bmodel = pascal(op["request_schema"].lstrip("[]"))
                    block.append(f"        {model_type(bmodel)} body;")
                    block.append("        memset(&body, 0, sizeof(body));")
                    args.append("&body")
                elif p["kind"] == "page":
                    args.append("NULL")
                elif p["kind"] == "out":
                    decl = p["decl"].rstrip(" *")
                    block.append(f"        {decl} *result = NULL;")
                    args.append("&result")
                    m = snake(pascal(op["response"]["schema"].lstrip("[]")))
                    k = op["response"]["kind"]
                    frees.append(f"axiam_mgmt_{m}_page_free(result);" if k == "page"
                                 else f"axiam_mgmt_{m}_list_free(result);" if k == "array"
                                 else f"axiam_mgmt_{m}_free(result);")
                elif p["kind"] == "err":
                    args.append("&err")

            block.append("        arm(n);")
            block.append(f"        (void) {op_symbol(namespace, opname)}(" + ", ".join(args) + ");")
            block.append("        disarm();")
            for free in frees:
                block.append(f"        {free}")
            block.append("        axiam_client_free(c);")
            block.append("    }")
            block.extend(comment(
                "Reaching here at all is the assertion: no crash, no double free, and "
                "under ASan no leak, with each of the first ALLOC_DEPTH allocations "
                "failed in turn.", "    "))
            block.append("    TEST_PASS();")
            block.append("}")
            cases.append("\n".join(block))

    out.append("\n\n".join(cases))
    out.append("")
    out.append("int main(void) {")
    out.append("    UNITY_BEGIN();")
    for fn in names:
        out.append(f"    RUN_TEST({fn});")
    out.append("    return UNITY_END();")
    out.append("}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build() -> dict[Path, str]:
    """Every file this generator owns, keyed by absolute path."""
    files = {
        MODELS_H: emit_models_header(),
        OPS_H: emit_ops_header(),
        MODELS_C: emit_models_source(),
        OPS_C: emit_ops_source(),
        TEST_C: emit_test(),
        MODEL_TEST_C: emit_model_test(),
        ALLOC_TEST_C: emit_alloc_test(),
    }
    return {ROOT / path: text for path, text in files.items()}


def main() -> int:
    """Write (or, with ``--check``, verify) the generated 27 surface."""
    check = "--check" in sys.argv
    files = build()

    if check:
        drifted = [p for p, text in sorted(files.items())
                   if not p.exists() or p.read_text() != text]
        if drifted:
            for path in drifted:
                print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            print(
                "\nThe committed 27 surface disagrees with management-registry.json / "
                "openapi.json.\nRegenerate with `python3 scripts/gen_management.py` and "
                "commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"27 surface is current ({len(files)} files).")
        return 0

    for path, text in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
